//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace BR.Config {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class MonitoringConfig {
        
        private DBCluster accountDBField;
        
        private DBCluster[] gameDBField;
        
        private DBCluster[] rankingDBField;
        
        private DBCluster tableDBField;
        
        private Monitoring monitoringField;
        
        /// <remarks/>
        public DBCluster AccountDB {
            get {
                return this.accountDBField;
            }
            set {
                this.accountDBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GameDB")]
        public DBCluster[] GameDB {
            get {
                return this.gameDBField;
            }
            set {
                this.gameDBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RankingDB")]
        public DBCluster[] RankingDB {
            get {
                return this.rankingDBField;
            }
            set {
                this.rankingDBField = value;
            }
        }
        
        /// <remarks/>
        public DBCluster TableDB {
            get {
                return this.tableDBField;
            }
            set {
                this.tableDBField = value;
            }
        }
        
        /// <remarks/>
        public Monitoring Monitoring {
            get {
                return this.monitoringField;
            }
            set {
                this.monitoringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DBCluster {
        
        private string clusterNameField;
        
        private string connectionStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClusterName {
            get {
                return this.clusterNameField;
            }
            set {
                this.clusterNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ConnectionString {
            get {
                return this.connectionStringField;
            }
            set {
                this.connectionStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Monitoring {
        
        private int monitoringListenPortField;
        
        private bool monitoringListenPortFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int MonitoringListenPort {
            get {
                return this.monitoringListenPortField;
            }
            set {
                this.monitoringListenPortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MonitoringListenPortSpecified {
            get {
                return this.monitoringListenPortFieldSpecified;
            }
            set {
                this.monitoringListenPortFieldSpecified = value;
            }
        }
    }
}
