//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.6
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BR {

public class ArrayUInt32 : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ArrayUInt32(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ArrayUInt32 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ArrayUInt32() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BRMonitoringPINVOKE.delete_ArrayUInt32(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public unsafe uint GetSize() {
    uint ret = BRMonitoringPINVOKE.ArrayUInt32_GetSize(swigCPtr);
    return ret;
  }

  public unsafe uint size() {
    uint ret = BRMonitoringPINVOKE.ArrayUInt32_size(swigCPtr);
    return ret;
  }

  public unsafe SWIGTYPE_p_Result SetSize(uint szNewSize) {
    SWIGTYPE_p_Result ret = new SWIGTYPE_p_Result(BRMonitoringPINVOKE.ArrayUInt32_SetSize(swigCPtr, szNewSize), true);
    return ret;
  }

  public unsafe void resize(uint szNewSize) {
    BRMonitoringPINVOKE.ArrayUInt32_resize(swigCPtr, szNewSize);
  }

  public unsafe void Clear() {
    BRMonitoringPINVOKE.ArrayUInt32_Clear(swigCPtr);
  }

  public unsafe bool GetConserveDataOnResize() {
    bool ret = BRMonitoringPINVOKE.ArrayUInt32_GetConserveDataOnResize(swigCPtr);
    return ret;
  }

  public unsafe void SetConserveDataOnResize(bool conserveDataOnResize) {
    BRMonitoringPINVOKE.ArrayUInt32_SetConserveDataOnResize(swigCPtr, conserveDataOnResize);
  }

  public unsafe uint GetAllocatedSize() {
    uint ret = BRMonitoringPINVOKE.ArrayUInt32_GetAllocatedSize(swigCPtr);
    return ret;
  }

  public unsafe uint GetIncreaseSize() {
    uint ret = BRMonitoringPINVOKE.ArrayUInt32_GetIncreaseSize(swigCPtr);
    return ret;
  }

  public unsafe void SetIncreaseSize(uint szNewIncSize) {
    BRMonitoringPINVOKE.ArrayUInt32_SetIncreaseSize(swigCPtr, szNewIncSize);
  }

  public unsafe SWIGTYPE_p_Result Reserve(uint szReserv) {
    SWIGTYPE_p_Result ret = new SWIGTYPE_p_Result(BRMonitoringPINVOKE.ArrayUInt32_Reserve(swigCPtr, szReserv), true);
    return ret;
  }

  public unsafe SWIGTYPE_p_unsigned_int data() {
    global::System.IntPtr cPtr = BRMonitoringPINVOKE.ArrayUInt32_data(swigCPtr);
    SWIGTYPE_p_unsigned_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
    return ret;
  }

  public unsafe SWIGTYPE_p_Result push_back(uint NewData) {
    SWIGTYPE_p_Result ret = new SWIGTYPE_p_Result(BRMonitoringPINVOKE.ArrayUInt32_push_back(swigCPtr, NewData), true);
    return ret;
  }

  public unsafe SWIGTYPE_p_Result AddItems(uint numItems, SWIGTYPE_p_unsigned_int NewData) {
    SWIGTYPE_p_Result ret = new SWIGTYPE_p_Result(BRMonitoringPINVOKE.ArrayUInt32_AddItems(swigCPtr, numItems, SWIGTYPE_p_unsigned_int.getCPtr(NewData)), true);
    return ret;
  }

  public unsafe SWIGTYPE_p_Result RemoveAt(int iIndex) {
    SWIGTYPE_p_Result ret = new SWIGTYPE_p_Result(BRMonitoringPINVOKE.ArrayUInt32_RemoveAt(swigCPtr, iIndex), true);
    return ret;
  }

  public unsafe SWIGTYPE_p_Result RemoveItem(uint RemoveData) {
    SWIGTYPE_p_Result ret = new SWIGTYPE_p_Result(BRMonitoringPINVOKE.ArrayUInt32_RemoveItem(swigCPtr, RemoveData), true);
    return ret;
  }

  public unsafe int FindItem(uint FindData) {
    int ret = BRMonitoringPINVOKE.ArrayUInt32_FindItem(swigCPtr, FindData);
    return ret;
  }

  public unsafe uint GetAt(uint iElement) {
    uint ret = BRMonitoringPINVOKE.ArrayUInt32_GetAt(swigCPtr, iElement);
    return ret;
  }

}

}
