//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.6
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BR {

public class ArrayPerformanceCounterInstanceInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ArrayPerformanceCounterInstanceInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ArrayPerformanceCounterInstanceInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ArrayPerformanceCounterInstanceInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BRMonitoringPINVOKE.delete_ArrayPerformanceCounterInstanceInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public unsafe uint GetSize() {
    uint ret = BRMonitoringPINVOKE.ArrayPerformanceCounterInstanceInfo_GetSize(swigCPtr);
    return ret;
  }

  public unsafe uint size() {
    uint ret = BRMonitoringPINVOKE.ArrayPerformanceCounterInstanceInfo_size(swigCPtr);
    return ret;
  }

  public unsafe SWIGTYPE_p_Result SetSize(uint szNewSize) {
    SWIGTYPE_p_Result ret = new SWIGTYPE_p_Result(BRMonitoringPINVOKE.ArrayPerformanceCounterInstanceInfo_SetSize(swigCPtr, szNewSize), true);
    return ret;
  }

  public unsafe void resize(uint szNewSize) {
    BRMonitoringPINVOKE.ArrayPerformanceCounterInstanceInfo_resize(swigCPtr, szNewSize);
  }

  public unsafe void Clear() {
    BRMonitoringPINVOKE.ArrayPerformanceCounterInstanceInfo_Clear(swigCPtr);
  }

  public unsafe bool GetConserveDataOnResize() {
    bool ret = BRMonitoringPINVOKE.ArrayPerformanceCounterInstanceInfo_GetConserveDataOnResize(swigCPtr);
    return ret;
  }

  public unsafe void SetConserveDataOnResize(bool conserveDataOnResize) {
    BRMonitoringPINVOKE.ArrayPerformanceCounterInstanceInfo_SetConserveDataOnResize(swigCPtr, conserveDataOnResize);
  }

  public unsafe uint GetAllocatedSize() {
    uint ret = BRMonitoringPINVOKE.ArrayPerformanceCounterInstanceInfo_GetAllocatedSize(swigCPtr);
    return ret;
  }

  public unsafe uint GetIncreaseSize() {
    uint ret = BRMonitoringPINVOKE.ArrayPerformanceCounterInstanceInfo_GetIncreaseSize(swigCPtr);
    return ret;
  }

  public unsafe void SetIncreaseSize(uint szNewIncSize) {
    BRMonitoringPINVOKE.ArrayPerformanceCounterInstanceInfo_SetIncreaseSize(swigCPtr, szNewIncSize);
  }

  public unsafe SWIGTYPE_p_Result Reserve(uint szReserv) {
    SWIGTYPE_p_Result ret = new SWIGTYPE_p_Result(BRMonitoringPINVOKE.ArrayPerformanceCounterInstanceInfo_Reserve(swigCPtr, szReserv), true);
    return ret;
  }

  public unsafe PerformanceCounterInstanceInfo data() {
    global::System.IntPtr cPtr = BRMonitoringPINVOKE.ArrayPerformanceCounterInstanceInfo_data(swigCPtr);
    PerformanceCounterInstanceInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new PerformanceCounterInstanceInfo(cPtr, false);
    return ret;
  }

  public unsafe SWIGTYPE_p_Result push_back(PerformanceCounterInstanceInfo NewData) {
    SWIGTYPE_p_Result ret = new SWIGTYPE_p_Result(BRMonitoringPINVOKE.ArrayPerformanceCounterInstanceInfo_push_back(swigCPtr, PerformanceCounterInstanceInfo.getCPtr(NewData)), true);
    if (BRMonitoringPINVOKE.SWIGPendingException.Pending) throw BRMonitoringPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe SWIGTYPE_p_Result AddItems(uint numItems, PerformanceCounterInstanceInfo NewData) {
    SWIGTYPE_p_Result ret = new SWIGTYPE_p_Result(BRMonitoringPINVOKE.ArrayPerformanceCounterInstanceInfo_AddItems(swigCPtr, numItems, PerformanceCounterInstanceInfo.getCPtr(NewData)), true);
    return ret;
  }

  public unsafe SWIGTYPE_p_Result RemoveAt(int iIndex) {
    SWIGTYPE_p_Result ret = new SWIGTYPE_p_Result(BRMonitoringPINVOKE.ArrayPerformanceCounterInstanceInfo_RemoveAt(swigCPtr, iIndex), true);
    return ret;
  }

  public unsafe SWIGTYPE_p_Result RemoveItem(PerformanceCounterInstanceInfo RemoveData) {
    SWIGTYPE_p_Result ret = new SWIGTYPE_p_Result(BRMonitoringPINVOKE.ArrayPerformanceCounterInstanceInfo_RemoveItem(swigCPtr, PerformanceCounterInstanceInfo.getCPtr(RemoveData)), true);
    if (BRMonitoringPINVOKE.SWIGPendingException.Pending) throw BRMonitoringPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe int FindItem(PerformanceCounterInstanceInfo FindData) {
    int ret = BRMonitoringPINVOKE.ArrayPerformanceCounterInstanceInfo_FindItem(swigCPtr, PerformanceCounterInstanceInfo.getCPtr(FindData));
    if (BRMonitoringPINVOKE.SWIGPendingException.Pending) throw BRMonitoringPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe PerformanceCounterInstanceInfo GetAt(uint iElement) {
    PerformanceCounterInstanceInfo ret = new PerformanceCounterInstanceInfo(BRMonitoringPINVOKE.ArrayPerformanceCounterInstanceInfo_GetAt(swigCPtr, iElement), false);
    return ret;
  }

}

}
