//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.6
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BR {

public enum ClusterID {
  EntityManager = 1,
  ClusterManager,
  Monitoring,
  Login,
  Game,
  Game_Conspiracy,
  Game_Max,
  GameInstanceManager = Game_Max,
  GamePartyManager,
  Ranking,
  PurchaseValidateGoogle,
  PurchaseValidateIOS,
  Matching_Game_4,
  Matching_Game_8,
  MatchingQueue_Game_4x1 = 50,
  MatchingQueue_Game_4x2,
  MatchingQueue_Game_4x3,
  MatchingQueue_Game_4x1S,
  MatchingQueue_Game_4x1W,
  MatchingQueue_Game_8x1,
  MatchingQueue_Game_8x2,
  MatchingQueue_Game_8x3,
  MatchingQueue_Game_8x4,
  MatchingQueue_Game_8x5,
  MatchingQueue_Game_8x6,
  MatchingQueue_Game_8x7,
  MatchingQueue_Game_8x1S,
  MatchingQueue_Game_8x1W,
  Max,
  MatchingQueue_Max = MatchingQueue_Game_8x1W
}

}
