//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.6
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BR {

public class GameLogVoteResult : GameLogItem {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal GameLogVoteResult(global::System.IntPtr cPtr, bool cMemoryOwn) : base(BRMonitoringPINVOKE.GameLogVoteResult_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GameLogVoteResult obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public unsafe uint NumberOfRanker {
    set {
      BRMonitoringPINVOKE.GameLogVoteResult_NumberOfRanker_set(swigCPtr, value);
    } 
    get {
      uint ret = BRMonitoringPINVOKE.GameLogVoteResult_NumberOfRanker_get(swigCPtr);
      return ret;
    } 
  }

  public unsafe SWIGTYPE_p_unsigned___int64 VotedRankers {
    set {
      BRMonitoringPINVOKE.GameLogVoteResult_VotedRankers_set(swigCPtr, SWIGTYPE_p_unsigned___int64.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BRMonitoringPINVOKE.GameLogVoteResult_VotedRankers_get(swigCPtr);
      SWIGTYPE_p_unsigned___int64 ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned___int64(cPtr, false);
      return ret;
    } 
  }

  public unsafe GameLogVoteResult(uint timeStamp, uint numRankers) : this(BRMonitoringPINVOKE.new_GameLogVoteResult(timeStamp, numRankers), true) {
  }

  public unsafe void SetVotedRankers(uint numRankers, SWIGTYPE_p_unsigned___int64 ranker) {
    BRMonitoringPINVOKE.GameLogVoteResult_SetVotedRankers(swigCPtr, numRankers, SWIGTYPE_p_unsigned___int64.getCPtr(ranker));
  }

}

}
