//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.6
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BR {

public class MessageBase : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MessageBase(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MessageBase obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MessageBase() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BRMonitoringPINVOKE.delete_MessageBase(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public unsafe MessageData GetMessage() {
    global::System.IntPtr cPtr = BRMonitoringPINVOKE.MessageBase_GetMessage(swigCPtr);
    MessageData ret = (cPtr == global::System.IntPtr.Zero) ? null : new MessageData(cPtr, false);
    return ret;
  }

  public unsafe SWIGTYPE_p_Result GetParsingResult() {
    SWIGTYPE_p_Result ret = new SWIGTYPE_p_Result(BRMonitoringPINVOKE.MessageBase_GetParsingResult(swigCPtr), true);
    return ret;
  }

  public unsafe SWIGTYPE_p_Result ParseMsg() {
    SWIGTYPE_p_Result ret = new SWIGTYPE_p_Result(BRMonitoringPINVOKE.MessageBase_ParseMsg(swigCPtr), true);
    return ret;
  }

  public unsafe SWIGTYPE_p_Result ParseIMsg(MessageData pIMsg) {
    SWIGTYPE_p_Result ret = new SWIGTYPE_p_Result(BRMonitoringPINVOKE.MessageBase_ParseIMsg(swigCPtr, MessageData.getCPtr(pIMsg)), true);
    return ret;
  }

  public unsafe SWIGTYPE_p_Result OverrideRouteContextDestination(EntityUID to) {
    SWIGTYPE_p_Result ret = new SWIGTYPE_p_Result(BRMonitoringPINVOKE.MessageBase_OverrideRouteContextDestination(swigCPtr, EntityUID.getCPtr(to)), true);
    if (BRMonitoringPINVOKE.SWIGPendingException.Pending) throw BRMonitoringPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe SWIGTYPE_p_Result OverrideRouteInfomation(EntityUID to, uint hopCount) {
    SWIGTYPE_p_Result ret = new SWIGTYPE_p_Result(BRMonitoringPINVOKE.MessageBase_OverrideRouteInfomation(swigCPtr, EntityUID.getCPtr(to), hopCount), true);
    if (BRMonitoringPINVOKE.SWIGPendingException.Pending) throw BRMonitoringPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
