//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.6
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BR {

public class MessageHeader : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MessageHeader(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MessageHeader obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public unsafe MessageID msgID {
    set {
      BRMonitoringPINVOKE.MessageHeader_msgID_set(swigCPtr, MessageID.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = BRMonitoringPINVOKE.MessageHeader_msgID_get(swigCPtr);
      MessageID ret = (cPtr == global::System.IntPtr.Zero) ? null : new MessageID(cPtr, false);
      return ret;
    } 
  }

  public unsafe uint Length {
    set {
      BRMonitoringPINVOKE.MessageHeader_Length_set(swigCPtr, value);
    } 
    get {
      uint ret = BRMonitoringPINVOKE.MessageHeader_Length_get(swigCPtr);
      return ret;
    } 
  }

  public unsafe uint Crc32 {
    set {
      BRMonitoringPINVOKE.MessageHeader_Crc32_set(swigCPtr, value);
    } 
    get {
      uint ret = BRMonitoringPINVOKE.MessageHeader_Crc32_get(swigCPtr);
      return ret;
    } 
  }

}

}
