//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BR {

public class MobileMessageHeader : MessageHeader {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal MobileMessageHeader(global::System.IntPtr cPtr, bool cMemoryOwn) : base(BRMonitoringPINVOKE.MobileMessageHeader_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MobileMessageHeader obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public unsafe ulong PeerID {
    set {
      BRMonitoringPINVOKE.MobileMessageHeader_PeerID_set(swigCPtr, value);
    } 
    get {
      ulong ret = BRMonitoringPINVOKE.MobileMessageHeader_PeerID_get(swigCPtr);
      return ret;
    } 
  }

}

}
