//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.6
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BR {

public class NetSvrPolicyRanking : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal NetSvrPolicyRanking(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(NetSvrPolicyRanking obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public unsafe NetSvrPolicyRanking(IConnection pConn) : this(BRMonitoringPINVOKE.new_NetSvrPolicyRanking(IConnection.getCPtr(pConn)), true) {
  }

  public unsafe int AddPlayerRes(ulong InContext, int InResult, RouteContext InRouteContext, uint InRanking) {
    int ret = BRMonitoringPINVOKE.NetSvrPolicyRanking_AddPlayerRes(swigCPtr, InContext, InResult, RouteContext.getCPtr(InRouteContext), InRanking);
    if (BRMonitoringPINVOKE.SWIGPendingException.Pending) throw BRMonitoringPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe int RemovePlayerRes(ulong InContext, int InResult, RouteContext InRouteContext) {
    int ret = BRMonitoringPINVOKE.NetSvrPolicyRanking_RemovePlayerRes(swigCPtr, InContext, InResult, RouteContext.getCPtr(InRouteContext));
    if (BRMonitoringPINVOKE.SWIGPendingException.Pending) throw BRMonitoringPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe int GetPlayerRankingRes(ulong InContext, int InResult, RouteContext InRouteContext, uint InRanking) {
    int ret = BRMonitoringPINVOKE.NetSvrPolicyRanking_GetPlayerRankingRes(swigCPtr, InContext, InResult, RouteContext.getCPtr(InRouteContext), InRanking);
    if (BRMonitoringPINVOKE.SWIGPendingException.Pending) throw BRMonitoringPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe int UpdatePlayerRes(ulong InContext, int InResult, RouteContext InRouteContext, uint InRanking) {
    int ret = BRMonitoringPINVOKE.NetSvrPolicyRanking_UpdatePlayerRes(swigCPtr, InContext, InResult, RouteContext.getCPtr(InRouteContext), InRanking);
    if (BRMonitoringPINVOKE.SWIGPendingException.Pending) throw BRMonitoringPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe int GetRankingRes(ulong InContext, int InResult, RouteContext InRouteContext, uint InPlayerRanking) {
    int ret = BRMonitoringPINVOKE.NetSvrPolicyRanking_GetRankingRes(swigCPtr, InContext, InResult, RouteContext.getCPtr(InRouteContext), InPlayerRanking);
    if (BRMonitoringPINVOKE.SWIGPendingException.Pending) throw BRMonitoringPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
