////////////////////////////////////////////////////////////////////////////////
// 
// CopyRight (c) 2016 Blue3k
// 
// Author : KyungKun Ko
//
// Description : Autogenerated header, Game
//
////////////////////////////////////////////////////////////////////////////////

#include <stdint.h>



// User is already in a game 
#define E_GAME_ALREADY_IN_GAME                                        ((int32_t)0xE7070000L) 

// Invalid player 
#define E_GAME_INVALID_PLAYER                                         ((int32_t)0xE7070001L) 

// Game is not ready 
#define E_GAME_NOTREADY                                               ((int32_t)0xE7070002L) 

// Invalid player role 
#define E_GAME_INVALID_ROLE                                           ((int32_t)0xE7070003L) 

// Not ready for next game play state 
#define E_GAME_NOT_READY_FOR_NEXT_STATE                               ((int32_t)0xE7070004L) 

// Invalid vote type 
#define E_GAME_INVALID_VOTETYPE                                       ((int32_t)0xE7070005L) 

// Invalid vote state 
#define E_GAME_INVALID_VOTE_STATE                                     ((int32_t)0xE7070006L) 

// Invalid vote target 
#define E_GAME_INVALID_VOTE_TARGET                                    ((int32_t)0xE7070007L) 

// No suffrage 
#define E_GAME_NO_SUFFRAGE                                            ((int32_t)0xE7070008L) 

// Invalid game state 
#define E_GAME_INVALID_GAMESTATE                                      ((int32_t)0xE7070009L) 

// Invalid partyID 
#define E_GAME_INVALID_PARTYID                                        ((int32_t)0xE707000AL) 

// Invalid player count for game 
#define E_GAME_INVALID_PLAYER_COUNT                                   ((int32_t)0xE707000BL) 

// User is already in a party 
#define E_GAME_ALREADY_IN_PARTY                                       ((int32_t)0xE707000CL) 

// User doesn't have eligible privilege 
#define E_GAME_NO_PRIVILEGE                                           ((int32_t)0xE707000DL) 

// Invalid shop item data 
#define E_GAME_INVALID_SHOPITEM                                       ((int32_t)0xE707000EL) 

// Invalid shop item id 
#define E_GAME_INVALID_SHOPITEMID                                     ((int32_t)0xE707000FL) 

// Not enough money(gold, gem, etc) 
#define E_GAME_NOTENOUGH_RESOURCE                                     ((int32_t)0xE7070010L) 

// Doesn't have enough stamina 
#define E_GAME_LOW_STAMINA                                            ((int32_t)0xE7070011L) 

// Invalid player game state 
#define E_GAME_INVALID_PLAYER_STATE                                   ((int32_t)0xE7070012L) 

// Maximum notification count 
#define E_GAME_MAX_NOTIFICATION                                       ((int32_t)0xE7070013L) 

// Maximum try reached 
#define E_GAME_MAX_TRY                                                ((int32_t)0xE7070014L) 

// Invalid cost table id 
#define E_GAME_INVALID_COSTID                                         ((int32_t)0xE7070015L) 

// Invalid bot talk table 
#define E_GAME_INVALID_BOTTALK_TABLE                                  ((int32_t)0xE7070016L) 


