////////////////////////////////////////////////////////////////////////////////
// 
// CopyRight (c) 2016 Blue3k
// 
// Author : KyungKun Ko
//
// Description : Autogenerated header, Net
//
////////////////////////////////////////////////////////////////////////////////

#pragma once
#include <stdint.h>



namespace BR {
	namespace ResultCode {

		enum {


			// Network sequence already processed 
			S_NET_PROCESSED_SEQUENCE                                           = 0x27030000L, 

			// The version not available or miss match with system. 
			E_NET_PROTOCOL_VERSION_MISMATCH                                    = 0xE7030001L, 

			// Network is not initialized 
			E_NET_NOTINITIALIZED                                               = 0xE7030002L, 

			// The version not available or miss match with system. 
			E_NET_INVALID_NETCLASS                                             = 0xE7030003L, 

			// Not enough space in sliding window 
			E_NET_NOT_ENOUGH_WINDOWSPACE                                       = 0xE7030004L, 

			// Network IO aborted 
			E_NET_IO_ABORTED                                                   = 0xE7030005L, 

			// Network IO send failed 
			E_NET_IO_SEND_FAIL                                                 = 0xE7030006L, 

			// Network IO recv failed 
			E_NET_IO_RECV_FAIL                                                 = 0xE7030007L, 

			// Network send failed 
			E_NET_SEND_FAIL                                                    = 0xE7030008L, 

			// Network recv failed 
			E_NET_RECV_FAIL                                                    = 0xE7030009L, 

			// Network Message sequence is invalid 
			E_NET_INVALID_SEQUENCE                                             = 0xE703000AL, 

			// Network Message not expected bad packet size 
			E_NET_BADPACKET_SIZE                                               = 0xE703000BL, 

			// Network connection closed 
			E_NET_CONNECTION_CLOSED                                            = 0xE703000CL, 

			// Network connection is never made 
			E_NET_NOT_CONNECTED                                                = 0xE703000DL, 

			// Network connection ID is invalid 
			E_NET_INVALID_CID                                                  = 0xE703000EL, 

			// Network Connection timeout 
			E_NET_CONNECTION_TIMEOUT                                           = 0xE703000FL, 

			// Network connection is failed 
			E_NET_CONNECTION_FAIL                                              = 0xE7030010L, 

			// Too big packet data 
			E_NET_BADPACKET_TOOBIG                                             = 0xE7030011L, 

			// Network Message not expected bad packet 
			E_NET_BADPACKET_NOTEXPECTED                                        = 0xE7030012L, 

			// Checksum value of the message is invalid 
			E_NET_INVALID_MESSAGE_CHECKSUM                                     = 0xE7030013L, 

			// Message encryption is invalid 
			E_NET_INVALID_MESSAGE_ENCRYPTION                                   = 0xE7030014L, 

			// Invalid connection state 
			E_NET_INVALID_CONNECTION_STATE                                     = 0xE7030015L, 

			// Too big sequence id 
			E_NET_SEQUENCE_OVERFLOW                                            = 0xE7030016L, 

			// A blocking operation was interrupted by a call to WSACancelBlockingCall. 
			E_NET_INTR                                                         = 0xE7030017L, 

			// The file handle supplied is not valid. 
			E_NET_BADF                                                         = 0xE7030018L, 

			// An attempt was made to access a socket in a way forbidden by its access permissions 
			E_NET_ACCES                                                        = 0xE7030019L, 

			// The system detected an invalid pointer address in attempting to use a pointer argument in a call. 
			E_NET_FAULT                                                        = 0xE703001AL, 

			// An invalid argument was supplied. 
			E_NET_INVAL                                                        = 0xE703001BL, 

			// Too many open sockets. 
			E_NET_MFILE                                                        = 0xE703001CL, 

			// A non-blocking socket operation could not be completed immediately. 
			E_NET_WOULDBLOCK                                                   = 0xE703001DL, 

			// A blocking operation is currently executing. 
			E_NET_INPROGRESS                                                   = 0xE703001EL, 

			// An operation was attempted on a non-blocking socket that already had an operation in progress. 
			E_NET_ALREADY                                                      = 0xE703001FL, 

			// An operation was attempted on something that is not a socket. 
			E_NET_NOTSOCK                                                      = 0xE7030020L, 

			// A required address was omitted from an operation on a socket. 
			E_NET_DESTADDRREQ                                                  = 0xE7030021L, 

			// A socket operation encountered a dead network. 
			E_NET_NETDOWN                                                      = 0xE7030022L, 

			// A socket operation was attempted to an unreachable network. 
			E_NET_NETUNREACH                                                   = 0xE7030023L, 

			// The connection has been broken due to keep-alive activity detecting a failure while the operation was in progress. 
			E_NET_NETRESET                                                     = 0xE7030024L, 

			// An established connection was aborted by the software in your host machine. 
			E_NET_CONNABORTED                                                  = 0xE7030025L, 

			// An existing connection was forcibly closed by the remote host. 
			E_NET_CONNRESET                                                    = 0xE7030026L, 

			// An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full. 
			E_NET_NOBUFS                                                       = 0xE7030027L, 

			// A connect request was made on an already connected socket. 
			E_NET_ISCONN                                                       = 0xE7030028L, 

			// A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied. 
			E_NET_NOTCONN                                                      = 0xE7030029L, 

			// A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call. 
			E_NET_SHUTDOWN                                                     = 0xE703002AL, 

			// Too many references to some kernel object. 
			E_NET_TOOMANYREFS                                                  = 0xE703002BL, 

			// A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 
			E_NET_TIMEDOUT                                                     = 0xE703002CL, 

			// No connection could be made because the target machine actively refused it. 
			E_NET_CONNECTION_REFUSSED                                          = 0xE703002DL, 

			// Cannot translate name. 
			E_NET_LOOP                                                         = 0xE703002EL, 

			// Name component or name was too long. 
			E_NET_NAMETOOLONG                                                  = 0xE703002FL, 

			// A socket operation failed because the destination host was down. 
			E_NET_HOSTDOWN                                                     = 0xE7030030L, 

			// A socket operation was attempted to an unreachable host. 
			E_NET_HOSTUNREACH                                                  = 0xE7030031L, 

			// Cannot remove a directory that is not empty. 
			E_NET_NOTEMPTY                                                     = 0xE7030032L, 

			// A Windows Sockets implementation may have a limit on the number of applications that may use it simultaneously. 
			E_NET_PROCLIM                                                      = 0xE7030033L, 

			// WSAStartup cannot function at this time because the underlying system it uses to provide network services is currently unavailable. 
			E_NET_SYSNOTREADY                                                  = 0xE7030034L, 

			// The Windows Sockets version requested is not supported. 
			E_NET_VERNOTSUPPORTED                                              = 0xE7030035L, 

			// Either the application has not called WSAStartup, or WSAStartup failed. 
			E_NET_NOTINITIALISED                                               = 0xE7030036L, 

			// Returned by WSARecv or WSARecvFrom to indicate the remote party has initiated a graceful shutdown sequence. 
			E_NET_DISCON                                                       = 0xE7030037L, 

			// A system call has failed. 
			E_NET_SYSCALLFAILURE                                               = 0xE7030038L, 

			// Host not found. 
			E_NET_HOST_NOT_FOUND                                               = 0xE7030039L, 

			// Try again 
			E_NET_TRY_AGAIN                                                    = 0xE703003AL, 

			// IOPending 
			E_NET_IO_PENDING                                                   = 0xE703003BL, 

			// No such host is known securely. 
			E_NET_SECURE_HOST_NOT_FOUND                                        = 0xE703003CL, 

			// Protocol error 
			E_NET_PROTO                                                        = 0xE703003DL, 

			// Protocol wrong type for socket. 
			E_NET_PROTOTYPE                                                    = 0xE703003EL, 

			// Protocol not available 
			E_NET_NOPROTOOPT                                                   = 0xE703003FL, 

			// Machine is not on the network 
			E_NET_NONET                                                        = 0xE7030040L, 

			// Operation not supported on socket 
			E_NET_OPNOTSUPP                                                    = 0xE7030041L, 

			// An invalid value was provided for the ai_flags member of the pHints parameter. 
			E_NET_BADFLAGS                                                     = 0xE7030042L, 

			// Bad network family 
			E_NET_FAMILY                                                       = 0xE7030043L, 

			// The pServiceName parameter is not supported for the specified ai_socktype member of the pHints parameter. 
			E_NET_INVALID_SERVICE                                              = 0xE7030044L, 

			// Invalid network address 
			E_NET_INVALID_ADDRESS                                              = 0xE7030045L, 

			// Address in use 
			E_NET_ADDRINUSE                                                    = 0xE7030046L, 

			// Network Message not expected packet data 
			E_NET_BADPACKET                                                    = 0xE7030047L, 

			// Disconnected 
			E_NET_DISCONNECTED                                                 = 0xE7030048L, 

		};//enum 
	}//namespace ResultCode 
}//namespace SF 



