////////////////////////////////////////////////////////////////////////////////
// 
// CopyRight (c) 2016 Blue3k
// 
// Author : KyungKun Ko
//
// Description : Autogenerated header, System
//
////////////////////////////////////////////////////////////////////////////////

#include <stdint.h>



// Success 
#define S_SYSTEM_FALSE                                                ((int32_t)0x20000000L) 

// Invalid pointer 
#define E_SYSTEM_POINTER                                              ((int32_t)0xE0000001L) 

// Fail 
#define E_SYSTEM_FAIL                                                 ((int32_t)0xE0000002L) 

// Not implemented 
#define E_SYSTEM_NOTIMPL                                              ((int32_t)0xE0000003L) 

// Out of memory 
#define E_SYSTEM_OUTOFMEMORY                                          ((int32_t)0xE0000004L) 

// Unexpected 
#define E_SYSTEM_UNEXPECTED                                           ((int32_t)0xE0000005L) 

// Invalid argument 
#define E_SYSTEM_INVALIDARG                                           ((int32_t)0xE0000006L) 


