////////////////////////////////////////////////////////////////////////////////
// 
// CopyRight (c) 2016 Blue3k
// 
// Author : KyungKun Ko
//
// Description : Autogenerated header, Common
//
////////////////////////////////////////////////////////////////////////////////

#include <stdint.h>



// Called without initialization. 
#define E_NOT_INITIALIZED                                             ((int32_t)0xE7020000L) 

// The version not available or miss match with system. 
#define E_VERSION_NOT_AVAIL                                           ((int32_t)0xE7020001L) 

// Invalid Cluster Master server 
#define E_INVALID_CLUSTERMASTER                                       ((int32_t)0xE7020002L) 

// The version not available or miss match with system. 
#define E_INVALID_STATE                                               ((int32_t)0xE7020003L) 

// Invalid string format. 
#define E_INVALID_STR_FORMAT                                          ((int32_t)0xE7020004L) 

// ServerID is duplicated. 
#define E_DUPLICATED_SERVERID                                         ((int32_t)0xE7020005L) 

// Invalid entity 
#define E_INVALID_ENTITY                                              ((int32_t)0xE7020006L) 

// Invalid duplicated entity 
#define E_DUPLICATED_ENTITY                                           ((int32_t)0xE7020007L) 

// Invalid duplicated entity 
#define E_DUPLICATED_ENTITYID                                         ((int32_t)0xE7020008L) 

// Duplicated Account ID 
#define E_DUPLICATED_ACCOUNTID                                        ((int32_t)0xE7020009L) 

// Duplicated Player ID 
#define E_DUPLICATED_PLAYERID                                         ((int32_t)0xE702000AL) 

// Duplicated name 
#define E_DUPLICATED_NAME                                             ((int32_t)0xE702000BL) 

// Duplicated ID 
#define E_DUPLICATED_ID                                               ((int32_t)0xE702000CL) 

// Invalid duplicated entity 
#define E_INVALID_ACCOUNTID                                           ((int32_t)0xE702000DL) 

// Invalid ticket 
#define E_INVALID_TICKET                                              ((int32_t)0xE702000EL) 

// Invalid player ID 
#define E_INVALID_PLAYERID                                            ((int32_t)0xE702000FL) 

// Invalid value 
#define E_INVALID_VALUE                                               ((int32_t)0xE7020010L) 

// Invalid class value 
#define E_INVALID_CLASS                                               ((int32_t)0xE7020011L) 

// Invalid Difficulty 
#define E_INVALID_DIFFICULTY                                          ((int32_t)0xE7020012L) 

// Invalid registration to play 
#define E_INVALID_REGISTRATION                                        ((int32_t)0xE7020013L) 

// Invalid Channel ID 
#define E_INVALID_CHANNELID                                           ((int32_t)0xE7020014L) 

// Invalid Zone instance ID 
#define E_INVALID_INSTANCEID                                          ((int32_t)0xE7020015L) 

// Duplicated component 
#define E_DUPLICATED_COMPONENT                                        ((int32_t)0xE7020016L) 

// Maximum friend 
#define E_MAX_FRIEND                                                  ((int32_t)0xE7020017L) 

// Invalid player count for service 
#define E_INVALID_PLAYER_COUNT                                        ((int32_t)0xE7020018L) 

// Invalid player level 
#define E_INVALID_PLAYER_LEVEL                                        ((int32_t)0xE7020019L) 

// Invalid player nick 
#define E_INVALID_PLAYER_NICK                                         ((int32_t)0xE702001AL) 

// Invalid Notification ID 
#define E_INVALID_NOTIFICATIONID                                      ((int32_t)0xE702001BL) 

// Invalid Ranking range 
#define E_INVALID_RANKING_RANGE                                       ((int32_t)0xE702001CL) 

// Target Maximum friend 
#define E_TARGET_MAX_FRIEND                                           ((int32_t)0xE702001DL) 

// Invalid string data. 
#define E_INVALID_STR_DATA                                            ((int32_t)0xE702001EL) 

// Not authorized 
#define E_NOT_AUTORIZED                                               ((int32_t)0xE702001FL) 

// No permition 
#define E_NO_PERMITION                                                ((int32_t)0xE7020020L) 

// No file or directory 
#define E_NO_FILE_OR_DIR                                              ((int32_t)0xE7020021L) 

// No such process 
#define E_NO_SUCH_PROCESS                                             ((int32_t)0xE7020022L) 

// Interrupted system call 
#define E_INTERRUPTED_SYSCALL                                         ((int32_t)0xE7020023L) 

// I/O error 
#define E_IO_ERROR                                                    ((int32_t)0xE7020024L) 

// No such device or address 
#define E_NOT_DEVICE                                                  ((int32_t)0xE7020025L) 

// Arg list too long 
#define E_TOO_MANY_ARGLIST                                            ((int32_t)0xE7020026L) 

// Exec format error 
#define E_INVALID_EXEC_FROMAT                                         ((int32_t)0xE7020027L) 

// Bad file number 
#define E_INVALID_FILE_HANDLE                                         ((int32_t)0xE7020028L) 

// No child process 
#define E_NO_CHILD_PROCESS                                            ((int32_t)0xE7020029L) 

// Try again 
#define E_TRY_AGAIN                                                   ((int32_t)0xE702002AL) 

// Bad address 
#define E_INVALID_POINTER                                             ((int32_t)0xE702002BL) 

// Block device required 
#define E_NOT_BLOCK                                                   ((int32_t)0xE702002CL) 

// Busy 
#define E_BUSY                                                        ((int32_t)0xE702002DL) 

// File exists 
#define E_FILE_EXISTS                                                 ((int32_t)0xE702002EL) 

// Cross-device link 
#define E_CROSS_LINK                                                  ((int32_t)0xE702002FL) 

// No such device 
#define E_INVALID_DEVICE                                              ((int32_t)0xE7020030L) 

// Not a directory 
#define E_INVALID_DIRECTORY                                           ((int32_t)0xE7020031L) 

// Is a directory 
#define E_DIRECTORY                                                   ((int32_t)0xE7020032L) 

// Invalid argument 
#define E_INVALID_ARG                                                 ((int32_t)0xE7020033L) 

// File table overflow 
#define E_NOT_ENOUGH_FILE_TABLE                                       ((int32_t)0xE7020034L) 

// Too many open files 
#define E_TOO_MANY_OPENED_FILE                                        ((int32_t)0xE7020035L) 

// Not a typewriter 
#define E_INVALID_TYPEWRITER                                          ((int32_t)0xE7020036L) 

// Text file busy 
#define E_BUSY_FILE                                                   ((int32_t)0xE7020037L) 

// File too large 
#define E_TOO_BIG_FILE                                                ((int32_t)0xE7020038L) 

// No space left on device 
#define E_NOT_ENOUGH_SPACE                                            ((int32_t)0xE7020039L) 

// Illegal seek 
#define E_INVALID_SEEK                                                ((int32_t)0xE702003AL) 

// Read-only file system 
#define E_READ_ONLY                                                   ((int32_t)0xE702003BL) 

// Too many links 
#define E_TOO_MANY_LINK                                               ((int32_t)0xE702003CL) 

// Broken pipe 
#define E_INVALID_PIPE                                                ((int32_t)0xE702003DL) 

// Math argument out of domain of func 
#define E_INVALID_MATH_DOMAIN                                         ((int32_t)0xE702003EL) 

// Math result not representable 
#define E_INVALID_NUMERIC                                             ((int32_t)0xE702003FL) 

// Invalid password 
#define E_INVALID_PASSWORD                                            ((int32_t)0xE7020040L) 


