////////////////////////////////////////////////////////////////////////////////
// 
// CopyRight (c) 2016 Blue3k
// 
// Author : KyungKun Ko
//
// Description : Autogenerated header, DB
//
////////////////////////////////////////////////////////////////////////////////

#pragma once
#include <stdint.h>



namespace BR {
	namespace ResultCode {

		enum {


			// Database connection failed 
			E_DB_INVALID_CONFIG                                                = 0xE7050000L, 

			// Database connection failed 
			E_DB_CONNECTION_FAILED                                             = 0xE7050001L, 

			// Database connection lost 
			E_DB_CONNECTION_LOST                                               = 0xE7050002L, 

			// Database statement prepare is failed 
			E_DB_STATEMENT_PREPARE_FAILED                                      = 0xE7050003L, 

			// Database parameter binding is failed 
			E_DB_PARAMETER_BIND_FAILED                                         = 0xE7050004L, 

			// Database result patch is failed 
			E_DB_RESULT_PATCH_FAILED                                           = 0xE7050005L, 

			// Database result column count is mismatched 
			E_DB_RESULT_COUNT_MISMATCH                                         = 0xE7050006L, 

			// Database result column type is mismatched 
			E_DB_RESULT_FIELDTYPE_MISMATCH                                     = 0xE7050007L, 

			// Duplicated Database source is specified 
			E_DB_DUPLICATED_SOURCE                                             = 0xE7050008L, 

			// Invalid partitioning ID 
			E_DB_INVALID_PARTITIONINGID                                        = 0xE7050009L, 

			// Database not connected 
			E_DB_NOT_CONNECTED                                                 = 0xE705000AL, 

		};//enum 
	}//namespace ResultCode 
}//namespace SF 



