////////////////////////////////////////////////////////////////////////////////
// 
// CopyRight (c) 2016 Blue3k
// 
// Author : KyungKun Ko
//
// Description : Autogenerated header, Login
//
////////////////////////////////////////////////////////////////////////////////

#include <stdint.h>



// Invalid username 
#define E_LOGIN_INVALID_USERNAME                                      ((int32_t)0xE7060000L) 

// Invalid password 
#define E_LOGIN_INVALID_PASSWORD                                      ((int32_t)0xE7060001L) 

// Already logged in 
#define E_LOGIN_ALREADY_LOGGEDIN                                      ((int32_t)0xE7060002L) 

// Already logged in at another place, and failed to kick 
#define E_LOGIN_ALREADY_LOGGEDIN_OTHERPLACE                           ((int32_t)0xE7060003L) 

// Invalid user signature 
#define E_LOGIN_INVALID_SIGNATURE                                     ((int32_t)0xE7060004L) 


