////////////////////////////////////////////////////////////////////////////////
// 
// CopyRight (c) 2016 Blue3k
// 
// Author : KyungKun Ko
//
// Description : Autogenerated header, Svr
//
////////////////////////////////////////////////////////////////////////////////

#pragma once
#include <stdint.h>



namespace BR {
	namespace ResultCode {

		enum {


			// Server service failed 
			E_SVR_SERVICE_FAILED                                               = 0xE7040000L, 

			// Timed out 
			E_SVR_TIMEOUT                                                      = 0xE7040001L, 

			// Transaction has invalid state transition 
			E_SVR_TRANSACTION_INVALID_STATE                                    = 0xE7040002L, 

			// Server Transaction timed out 
			E_SVR_INVALID_TRANSITION                                           = 0xE7040003L, 

			// Transaction process Time out 
			E_SVR_TRANSACTION_TIMEOUT                                          = 0xE7040004L, 

			// Failed to route message 
			E_SVR_ROUTEMSG_FAILED                                              = 0xE7040005L, 

			// No result handler 
			E_SVR_NO_RESULT_HANDLER                                            = 0xE7040006L, 

			// No message handler 
			E_SVR_NO_MESSAGE_HANDLER                                           = 0xE7040007L, 

			// Invalid server ID 
			E_SVR_INVALID_SERVERID                                             = 0xE7040008L, 

			// Player not found 
			E_SVR_PLAYER_NOT_FOUND                                             = 0xE7040009L, 

			// Player state is invalid 
			E_SVR_INVALID_PLAYER_STATE                                         = 0xE704000AL, 

			// Invalid player game db data 
			E_SVR_INVALID_PLAYER_GAMEDB                                        = 0xE704000BL, 

			// Not expected server message 
			E_SVR_NOTEXPECTED_MESSAGE                                          = 0xE704000CL, 

			// Invalid entity UID 
			E_SVR_INVALID_ENTITYUID                                            = 0xE704000DL, 

			// Cluster service not ready 
			E_SVR_CLUSTER_NOTREADY                                             = 0xE704000EL, 

			// Invalid cluster type 
			E_SVR_INVALID_CLUSTERTYPE                                          = 0xE704000FL, 

			// Invalid cluster ID 
			E_SVR_INVALID_CLUSTERID                                            = 0xE7040010L, 

			// Invalid queue item 
			E_SVR_INVALID_QUEUEITEM                                            = 0xE7040011L, 

			// Queue item is canceled 
			E_SVR_QUEUEITEM_CANCELED                                           = 0xE7040012L, 

			// There is no item in queue 
			E_SVR_NOITEM_INQUEUE                                               = 0xE7040013L, 

			// Already in queue 
			E_SVR_ALREADY_INQUEUE                                              = 0xE7040014L, 

			// Queue item is reserved 
			E_SVR_RESERVED_QUEUEITEM                                           = 0xE7040015L, 

			// Cluster doesn't have any assigned master 
			E_SVR_CLUSTER_NOMASTER                                             = 0xE7040016L, 

			// Queue item is reserved for cancel 
			S_SVR_QUEUEITEM_CANCEL_PENDED                                      = 0x27040017L, 

			// Thread is wrong, running on wrong thread? 
			E_SVR_INVALID_THREAD                                               = 0xE7040018L, 

			// Purchase canceled 
			E_SVR_PURCHASE_CANCELED                                            = 0xE7040019L, 

			// Invalid receipt info 
			E_SVR_INVALID_PURCHASE_INFO                                        = 0xE704001AL, 

			// Invalid duplicated purchase 
			E_SVR_INVALID_PURCHASE_DUPLICATED                                  = 0xE704001BL, 

			// External auth fail 
			E_SVR_INVALID_EXTERNAL_AUTH                                        = 0xE704001CL, 

			// External server is not available 
			E_SVR_EXTERNAL_SERVER_UNAVALIABLE                                  = 0xE704001DL, 

			// Invalid receipt result from server 
			E_SVR_INVALID_PURCHASE_FORMAT                                      = 0xE704001EL, 

			// The protocol is not supported. 
			E_SVR_CURL_UNSUPPORTED_PROTOCOL                                    = 0xE704001FL, 

			// CURL initialization is failed. 
			E_SVR_CURL_FAILED_INIT                                             = 0xE7040020L, 

			// Invalid URL format. 
			E_SVR_CURL_URL_MALFORMAT                                           = 0xE7040021L, 

			// Not a build-in feature. 
			E_SVR_CURL_NOT_BUILT_IN                                            = 0xE7040022L, 

			// Failed to resolve URL. 
			E_SVR_CURL_COULDNT_RESOLVE_PROXY                                   = 0xE7040023L, 

			// Failed to resolve URL. 
			E_SVR_CURL_COULDNT_RESOLVE_HOST                                    = 0xE7040024L, 

			// Connection is failed 
			E_SVR_CURL_COULDNT_CONNECT                                         = 0xE7040025L, 

			// HTTP Post can't be done. 
			E_SVR_CURL_HTTP_POST_ERROR                                         = 0xE7040026L, 

			// Not supported SSL type. 
			E_SVR_CURL_SSL_ENGINE_NOTFOUND                                     = 0xE7040027L, 

			// Not supported SSL type. 
			E_SVR_CURL_SSL_ENGINE_SETFAILED                                    = 0xE7040028L, 

			// Network send failed 
			E_SVR_CURL_SEND_ERROR                                              = 0xE7040029L, 

			// Network receive failed 
			E_SVR_CURL_RECV_ERROR                                              = 0xE704002AL, 

			// Invalid SSL setting. 
			E_SVR_CURL_USE_SSL_FAILED                                          = 0xE704002BL, 

			// No Connection is available now. 
			E_SVR_CURL_NO_CONNECTION_AVAILABLE                                 = 0xE704002CL, 

			// Invalid state transition 
			E_SVR_INVALID_STATE                                                = 0xE704002DL, 

			// Invalid purchase environment(public/test) 
			E_SVR_INVALID_PURCHASE_MODE                                        = 0xE704002EL, 

		};//enum 
	}//namespace ResultCode 
}//namespace SF 



