////////////////////////////////////////////////////////////////////////////////
// 
// CopyRight (c) 2016 Blue3k
// 
// Author : KyungKun Ko
//
// Description : Autogenerated header, Common
//
////////////////////////////////////////////////////////////////////////////////

#pragma once
#include <stdint.h>



namespace BR {
	namespace ResultCode {

		enum {


			// Called without initialization. 
			E_NOT_INITIALIZED                                                  = 0xE7020000L, 

			// The version not available or miss match with system. 
			E_VERSION_NOT_AVAIL                                                = 0xE7020001L, 

			// Invalid Cluster Master server 
			E_INVALID_CLUSTERMASTER                                            = 0xE7020002L, 

			// The version not available or miss match with system. 
			E_INVALID_STATE                                                    = 0xE7020003L, 

			// Invalid string format. 
			E_INVALID_STR_FORMAT                                               = 0xE7020004L, 

			// ServerID is duplicated. 
			E_DUPLICATED_SERVERID                                              = 0xE7020005L, 

			// Invalid entity 
			E_INVALID_ENTITY                                                   = 0xE7020006L, 

			// Invalid duplicated entity 
			E_DUPLICATED_ENTITY                                                = 0xE7020007L, 

			// Invalid duplicated entity 
			E_DUPLICATED_ENTITYID                                              = 0xE7020008L, 

			// Duplicated Account ID 
			E_DUPLICATED_ACCOUNTID                                             = 0xE7020009L, 

			// Duplicated Player ID 
			E_DUPLICATED_PLAYERID                                              = 0xE702000AL, 

			// Duplicated name 
			E_DUPLICATED_NAME                                                  = 0xE702000BL, 

			// Duplicated ID 
			E_DUPLICATED_ID                                                    = 0xE702000CL, 

			// Invalid duplicated entity 
			E_INVALID_ACCOUNTID                                                = 0xE702000DL, 

			// Invalid ticket 
			E_INVALID_TICKET                                                   = 0xE702000EL, 

			// Invalid player ID 
			E_INVALID_PLAYERID                                                 = 0xE702000FL, 

			// Invalid value 
			E_INVALID_VALUE                                                    = 0xE7020010L, 

			// Invalid class value 
			E_INVALID_CLASS                                                    = 0xE7020011L, 

			// Invalid Difficulty 
			E_INVALID_DIFFICULTY                                               = 0xE7020012L, 

			// Invalid registration to play 
			E_INVALID_REGISTRATION                                             = 0xE7020013L, 

			// Invalid Channel ID 
			E_INVALID_CHANNELID                                                = 0xE7020014L, 

			// Invalid Zone instance ID 
			E_INVALID_INSTANCEID                                               = 0xE7020015L, 

			// Duplicated component 
			E_DUPLICATED_COMPONENT                                             = 0xE7020016L, 

			// Maximum friend 
			E_MAX_FRIEND                                                       = 0xE7020017L, 

			// Invalid player count for service 
			E_INVALID_PLAYER_COUNT                                             = 0xE7020018L, 

			// Invalid player level 
			E_INVALID_PLAYER_LEVEL                                             = 0xE7020019L, 

			// Invalid player nick 
			E_INVALID_PLAYER_NICK                                              = 0xE702001AL, 

			// Invalid Notification ID 
			E_INVALID_NOTIFICATIONID                                           = 0xE702001BL, 

			// Invalid Ranking range 
			E_INVALID_RANKING_RANGE                                            = 0xE702001CL, 

			// Target Maximum friend 
			E_TARGET_MAX_FRIEND                                                = 0xE702001DL, 

			// Invalid string data. 
			E_INVALID_STR_DATA                                                 = 0xE702001EL, 

			// Not authorized 
			E_NOT_AUTORIZED                                                    = 0xE702001FL, 

			// No permition 
			E_NO_PERMITION                                                     = 0xE7020020L, 

			// No file or directory 
			E_NO_FILE_OR_DIR                                                   = 0xE7020021L, 

			// No such process 
			E_NO_SUCH_PROCESS                                                  = 0xE7020022L, 

			// Interrupted system call 
			E_INTERRUPTED_SYSCALL                                              = 0xE7020023L, 

			// I/O error 
			E_IO_ERROR                                                         = 0xE7020024L, 

			// No such device or address 
			E_NOT_DEVICE                                                       = 0xE7020025L, 

			// Arg list too long 
			E_TOO_MANY_ARGLIST                                                 = 0xE7020026L, 

			// Exec format error 
			E_INVALID_EXEC_FROMAT                                              = 0xE7020027L, 

			// Bad file number 
			E_INVALID_FILE_HANDLE                                              = 0xE7020028L, 

			// No child process 
			E_NO_CHILD_PROCESS                                                 = 0xE7020029L, 

			// Try again 
			E_TRY_AGAIN                                                        = 0xE702002AL, 

			// Bad address 
			E_INVALID_POINTER                                                  = 0xE702002BL, 

			// Block device required 
			E_NOT_BLOCK                                                        = 0xE702002CL, 

			// Busy 
			E_BUSY                                                             = 0xE702002DL, 

			// File exists 
			E_FILE_EXISTS                                                      = 0xE702002EL, 

			// Cross-device link 
			E_CROSS_LINK                                                       = 0xE702002FL, 

			// No such device 
			E_INVALID_DEVICE                                                   = 0xE7020030L, 

			// Not a directory 
			E_INVALID_DIRECTORY                                                = 0xE7020031L, 

			// Is a directory 
			E_DIRECTORY                                                        = 0xE7020032L, 

			// Invalid argument 
			E_INVALID_ARG                                                      = 0xE7020033L, 

			// File table overflow 
			E_NOT_ENOUGH_FILE_TABLE                                            = 0xE7020034L, 

			// Too many open files 
			E_TOO_MANY_OPENED_FILE                                             = 0xE7020035L, 

			// Not a typewriter 
			E_INVALID_TYPEWRITER                                               = 0xE7020036L, 

			// Text file busy 
			E_BUSY_FILE                                                        = 0xE7020037L, 

			// File too large 
			E_TOO_BIG_FILE                                                     = 0xE7020038L, 

			// No space left on device 
			E_NOT_ENOUGH_SPACE                                                 = 0xE7020039L, 

			// Illegal seek 
			E_INVALID_SEEK                                                     = 0xE702003AL, 

			// Read-only file system 
			E_READ_ONLY                                                        = 0xE702003BL, 

			// Too many links 
			E_TOO_MANY_LINK                                                    = 0xE702003CL, 

			// Broken pipe 
			E_INVALID_PIPE                                                     = 0xE702003DL, 

			// Math argument out of domain of func 
			E_INVALID_MATH_DOMAIN                                              = 0xE702003EL, 

			// Math result not representable 
			E_INVALID_NUMERIC                                                  = 0xE702003FL, 

			// Invalid password 
			E_INVALID_PASSWORD                                                 = 0xE7020040L, 

			// Target already in friends list 
			E_ALREADY_IN_FRIEND                                                = 0xE7020041L, 

			// Thread is wrong, running on wrong thread? 
			E_INVALID_THREAD                                                   = 0xE7020042L, 

		};//enum 
	}//namespace ResultCode 
}//namespace SF 



