////////////////////////////////////////////////////////////////////////////////
// 
// CopyRight (c) 2016 Kyungkun Ko
// 
// Author : KyungKun Ko
//
// Description : Autogenerated header, Login
//
////////////////////////////////////////////////////////////////////////////////

#pragma once
#include <stdint.h>



namespace SF {
	namespace ResultCode {



			// Invalid username 
			constexpr Result 			LOGIN_INVALID_USERNAME                                             ((int32_t)0xE7150000L);

			// Invalid password 
			constexpr Result 			LOGIN_INVALID_PASSWORD                                             ((int32_t)0xE7150001L);

			// Already logged in 
			constexpr Result 			LOGIN_ALREADY_LOGGEDIN                                             ((int32_t)0xE7150002L);

			// Already logged in at another place, and failed to kick 
			constexpr Result 			LOGIN_ALREADY_LOGGEDIN_OTHERPLACE                                  ((int32_t)0xE7150003L);

			// Invalid user signature 
			constexpr Result 			LOGIN_INVALID_SIGNATURE                                            ((int32_t)0xE7150004L);

	}//namespace ResultCode 
}//namespace SF 





