////////////////////////////////////////////////////////////////////////////////
// 
// CopyRight (c) 2016 StormForge
// 
// Author : KyungKun Ko
//
// Description : Autogenerated header, DB
//
////////////////////////////////////////////////////////////////////////////////

#pragma once
#include <stdint.h>



namespace SF {
	namespace ResultCode {



			// Database connection failed 
			constexpr Result 			DB_INVALID_CONFIG                                                  (0xE7110000L);

			// Database connection failed 
			constexpr Result 			DB_CONNECTION_FAILED                                               (0xE7110001L);

			// Database connection lost 
			constexpr Result 			DB_CONNECTION_LOST                                                 (0xE7110002L);

			// Database statement prepare is failed 
			constexpr Result 			DB_STATEMENT_PREPARE_FAILED                                        (0xE7110003L);

			// Database parameter binding is failed 
			constexpr Result 			DB_PARAMETER_BIND_FAILED                                           (0xE7110004L);

			// Database result patch is failed 
			constexpr Result 			DB_RESULT_PATCH_FAILED                                             (0xE7110005L);

			// Database result column count is mismatched 
			constexpr Result 			DB_RESULT_COUNT_MISMATCH                                           (0xE7110006L);

			// Database result column type is mismatched 
			constexpr Result 			DB_RESULT_FIELDTYPE_MISMATCH                                       (0xE7110007L);

			// Duplicated Database source is specified 
			constexpr Result 			DB_DUPLICATED_SOURCE                                               (0xE7110008L);

			// Invalid partitioning ID 
			constexpr Result 			DB_INVALID_PARTITIONINGID                                          (0xE7110009L);

			// Database not connected 
			constexpr Result 			DB_NOT_CONNECTED                                                   (0xE711000AL);

	}//namespace ResultCode 
}//namespace SF 





