////////////////////////////////////////////////////////////////////////////////
// 
// CopyRight (c) 2016 Kyungkun Ko
// 
// Author : KyungKun Ko
//
// Description : Autogenerated header, Game
//
////////////////////////////////////////////////////////////////////////////////

#pragma once
#include <stdint.h>



namespace SF {
	namespace ResultCode {



			// User is already in a game 
			constexpr Result 			GAME_ALREADY_IN_GAME                                               ((int32_t)0xE7140000L);

			// Invalid player 
			constexpr Result 			GAME_INVALID_PLAYER                                                ((int32_t)0xE7140001L);

			// Game is not ready 
			constexpr Result 			GAME_NOTREADY                                                      ((int32_t)0xE7140002L);

			// Invalid player state to do the action 
			constexpr Result 			GAME_INVALID_PLAYER_STATE                                          ((int32_t)0xE7140003L);

			// Failed to find matching harvest id 
			constexpr Result 			GAME_NO_MATCHING_HARVEST_ID                                        ((int32_t)0xE7140004L);

			// Invalid shop item data 
			constexpr Result 			GAME_INVALID_SHOPITEM                                              ((int32_t)0xE7140005L);

			// Invalid shop item id 
			constexpr Result 			GAME_INVALID_SHOPITEMID                                            ((int32_t)0xE7140006L);

			// User is already in a party 
			constexpr Result 			GAME_ALREADY_IN_PARTY                                              ((int32_t)0xE7140007L);

			// Invalid partyID 
			constexpr Result 			GAME_INVALID_PARTYID                                               ((int32_t)0xE7140008L);

			// Invalid player count for game 
			constexpr Result 			GAME_INVALID_PLAYER_COUNT                                          ((int32_t)0xE7140009L);

			// User doesn't have eligible privilege 
			constexpr Result 			GAME_NO_PRIVILEGE                                                  ((int32_t)0xE714000AL);

			// Not enough money(gold, gem, etc) 
			constexpr Result 			GAME_NOTENOUGH_RESOURCE                                            ((int32_t)0xE714000BL);

			// Maximum notification count 
			constexpr Result 			GAME_MAX_NOTIFICATION                                              ((int32_t)0xE714000CL);

			// Maximum try reached 
			constexpr Result 			GAME_MAX_TRY                                                       ((int32_t)0xE714000DL);

			// User is already in a chatting channel 
			constexpr Result 			GAME_ALREADY_IN_CHAT                                               ((int32_t)0xE714000EL);

			// Map object is invalid 
			constexpr Result 			GAME_MAPOBJECT_INVALID                                             ((int32_t)0xE714000FL);

			// Map object is required to be occupied 
			constexpr Result 			GAME_OCCUPIED_MAPOBJECT_IS_REQUIRED                                ((int32_t)0xE7140010L);

			// Map object is already in use 
			constexpr Result 			GAME_MAPOBJECT_ALREADY_IN_USE                                      ((int32_t)0xE7140011L);

			// Map object is not in use 
			constexpr Result 			GAME_MAPOBJECT_NOT_IN_USE                                          ((int32_t)0xE7140012L);

			// Map object is already in use 
			constexpr Result 			GAME_MAPOBJECT_NOT_FOUND                                           ((int32_t)0xE7140013L);

			// Map object is not occupied by the player 
			constexpr Result 			GAME_MAPOBJECT_NOT_OCCUPIED_BY_PLAYER                              ((int32_t)0xE7140014L);

			// Invalid player role 
			constexpr Result 			GAME_INVALID_ROLE                                                  ((int32_t)0xE7140015L);

			// Not ready for next game play state 
			constexpr Result 			GAME_NOT_READY_FOR_NEXT_STATE                                      ((int32_t)0xE7140016L);

			// Invalid vote type 
			constexpr Result 			GAME_INVALID_VOTETYPE                                              ((int32_t)0xE7140017L);

			// Invalid vote state 
			constexpr Result 			GAME_INVALID_VOTE_STATE                                            ((int32_t)0xE7140018L);

			// Invalid vote target 
			constexpr Result 			GAME_INVALID_VOTE_TARGET                                           ((int32_t)0xE7140019L);

			// No suffrage 
			constexpr Result 			GAME_NO_SUFFRAGE                                                   ((int32_t)0xE714001AL);

			// Invalid game state 
			constexpr Result 			GAME_INVALID_GAMESTATE                                             ((int32_t)0xE714001BL);

			// Doesn't have enough stamina 
			constexpr Result 			GAME_LOW_STAMINA                                                   ((int32_t)0xE714001CL);

			// Invalid cost table id 
			constexpr Result 			GAME_INVALID_COSTID                                                ((int32_t)0xE714001DL);

			// Invalid bot talk table 
			constexpr Result 			GAME_INVALID_BOTTALK_TABLE                                         ((int32_t)0xE714001EL);

	}//namespace ResultCode 
}//namespace SF 





