#pragma once

#using <mscorlib.dll>
#using <System.dll>
#using <System.Data.dll>
#using <System.Xml.dll>

using namespace System::Security::Permissions;
[assembly:SecurityPermissionAttribute(SecurityAction::RequestMinimum, SkipVerification=false)];
// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
using namespace System;
ref class OrganicTbl;


/// <summary>
///Represents a strongly typed in-memory cache of data.
///</summary>
[System::Serializable, 
System::ComponentModel::DesignerCategoryAttribute(L"code"), 
System::ComponentModel::ToolboxItem(true), 
System::Xml::Serialization::XmlSchemaProviderAttribute(L"GetTypedDataSetSchema"), 
System::Xml::Serialization::XmlRootAttribute(L"OrganicTbl"), 
System::ComponentModel::Design::HelpKeywordAttribute(L"vs.data.DataSet")]
public ref class OrganicTbl : public ::System::Data::DataSet {
    public : ref class OrganicItemDataTable;
    public : ref class OrganicItemRow;
    public : ref class OrganicItemRowChangeEvent;
    
    private: OrganicTbl::OrganicItemDataTable^  tableOrganicItem;
    
    private: ::System::Data::SchemaSerializationMode _schemaSerializationMode;
    
    public : [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
    delegate System::Void OrganicItemRowChangeEventHandler(::System::Object^  sender, OrganicTbl::OrganicItemRowChangeEvent^  e);
    
    public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
    OrganicTbl();
    protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
    OrganicTbl(::System::Runtime::Serialization::SerializationInfo^  info, ::System::Runtime::Serialization::StreamingContext context);
    public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
    System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0"), 
    System::ComponentModel::Browsable(false), 
    System::ComponentModel::DesignerSerializationVisibility(::System::ComponentModel::DesignerSerializationVisibility::Content)]
    property OrganicTbl::OrganicItemDataTable^  OrganicItem {
        OrganicTbl::OrganicItemDataTable^  get();
    }
    
    public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
    System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0"), 
    System::ComponentModel::BrowsableAttribute(true), 
    System::ComponentModel::DesignerSerializationVisibilityAttribute(::System::ComponentModel::DesignerSerializationVisibility::Visible)]
    virtual property ::System::Data::SchemaSerializationMode SchemaSerializationMode {
        ::System::Data::SchemaSerializationMode get() override;
        System::Void set(::System::Data::SchemaSerializationMode value) override;
    }
    
    public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
    System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0"), 
    System::ComponentModel::DesignerSerializationVisibilityAttribute(::System::ComponentModel::DesignerSerializationVisibility::Hidden)]
    property ::System::Data::DataTableCollection^  Tables {
        ::System::Data::DataTableCollection^  get() new;
    }
    
    public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
    System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0"), 
    System::ComponentModel::DesignerSerializationVisibilityAttribute(::System::ComponentModel::DesignerSerializationVisibility::Hidden)]
    property ::System::Data::DataRelationCollection^  Relations {
        ::System::Data::DataRelationCollection^  get() new;
    }
    
    protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
    virtual ::System::Void InitializeDerivedDataSet() override;
    
    public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
    virtual ::System::Data::DataSet^  Clone() override;
    
    protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
    virtual ::System::Boolean ShouldSerializeTables() override;
    
    protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
    virtual ::System::Boolean ShouldSerializeRelations() override;
    
    protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
    virtual ::System::Void ReadXmlSerializable(::System::Xml::XmlReader^  reader) override;
    
    protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
    virtual ::System::Xml::Schema::XmlSchema^  GetSchemaSerializable() override;
    
    internal: [System::Diagnostics::DebuggerNonUserCodeAttribute]
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
    ::System::Void InitVars();
    
    internal: [System::Diagnostics::DebuggerNonUserCodeAttribute]
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
    ::System::Void InitVars(::System::Boolean initTable);
    
    private: [System::Diagnostics::DebuggerNonUserCodeAttribute]
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
    ::System::Void InitClass();
    
    private: [System::Diagnostics::DebuggerNonUserCodeAttribute]
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
    ::System::Boolean ShouldSerializeOrganicItem();
    
    private: [System::Diagnostics::DebuggerNonUserCodeAttribute]
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
    ::System::Void SchemaChanged(::System::Object^  sender, ::System::ComponentModel::CollectionChangeEventArgs^  e);
    
    public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
    static ::System::Xml::Schema::XmlSchemaComplexType^  GetTypedDataSetSchema(::System::Xml::Schema::XmlSchemaSet^  xs);
    
    public : /// <summary>
///Represents the strongly named DataTable class.
///</summary>
    [System::Serializable, 
    System::Xml::Serialization::XmlSchemaProviderAttribute(L"GetTypedTableSchema")]
    ref class OrganicItemDataTable : public ::System::Data::DataTable, public ::System::Collections::IEnumerable {
        
        private: ::System::Data::DataColumn^  columnOrganicItemID;
        
        private: ::System::Data::DataColumn^  columnItemInfo;
        
        private: ::System::Data::DataColumn^  columnRequiredGem;
        
        private: ::System::Data::DataColumn^  columnRequiredGameMoney;
        
        private: ::System::Data::DataColumn^  columnItemEffect;
        
        public: [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        event OrganicTbl::OrganicItemRowChangeEventHandler^  OrganicItemRowChanging;
        
        public: [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        event OrganicTbl::OrganicItemRowChangeEventHandler^  OrganicItemRowChanged;
        
        public: [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        event OrganicTbl::OrganicItemRowChangeEventHandler^  OrganicItemRowDeleting;
        
        public: [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        event OrganicTbl::OrganicItemRowChangeEventHandler^  OrganicItemRowDeleted;
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        OrganicItemDataTable();
        internal: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        OrganicItemDataTable(::System::Data::DataTable^  table);
        protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        OrganicItemDataTable(::System::Runtime::Serialization::SerializationInfo^  info, ::System::Runtime::Serialization::StreamingContext context);
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        property ::System::Data::DataColumn^  OrganicItemIDColumn {
            ::System::Data::DataColumn^  get();
        }
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        property ::System::Data::DataColumn^  ItemInfoColumn {
            ::System::Data::DataColumn^  get();
        }
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        property ::System::Data::DataColumn^  RequiredGemColumn {
            ::System::Data::DataColumn^  get();
        }
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        property ::System::Data::DataColumn^  RequiredGameMoneyColumn {
            ::System::Data::DataColumn^  get();
        }
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        property ::System::Data::DataColumn^  ItemEffectColumn {
            ::System::Data::DataColumn^  get();
        }
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0"), 
        System::ComponentModel::Browsable(false)]
        property ::System::Int32 Count {
            ::System::Int32 get();
        }
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        property OrganicTbl::OrganicItemRow^  default [::System::Int32 ] {
            OrganicTbl::OrganicItemRow^  get(::System::Int32 index);
        }
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        ::System::Void AddOrganicItemRow(OrganicTbl::OrganicItemRow^  row);
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        OrganicTbl::OrganicItemRow^  AddOrganicItemRow(System::Int32 OrganicItemID, System::String^  ItemInfo, System::Int32 RequiredGem, 
                    System::Int32 RequiredGameMoney, System::String^  ItemEffect);
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        virtual ::System::Collections::IEnumerator^  GetEnumerator();
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        virtual ::System::Data::DataTable^  Clone() override;
        
        protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        virtual ::System::Data::DataTable^  CreateInstance() override;
        
        internal: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        ::System::Void InitVars();
        
        private: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        ::System::Void InitClass();
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        OrganicTbl::OrganicItemRow^  NewOrganicItemRow();
        
        protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        virtual ::System::Data::DataRow^  NewRowFromBuilder(::System::Data::DataRowBuilder^  builder) override;
        
        protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        virtual ::System::Type^  GetRowType() override;
        
        protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        virtual ::System::Void OnRowChanged(::System::Data::DataRowChangeEventArgs^  e) override;
        
        protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        virtual ::System::Void OnRowChanging(::System::Data::DataRowChangeEventArgs^  e) override;
        
        protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        virtual ::System::Void OnRowDeleted(::System::Data::DataRowChangeEventArgs^  e) override;
        
        protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        virtual ::System::Void OnRowDeleting(::System::Data::DataRowChangeEventArgs^  e) override;
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        ::System::Void RemoveOrganicItemRow(OrganicTbl::OrganicItemRow^  row);
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        static ::System::Xml::Schema::XmlSchemaComplexType^  GetTypedTableSchema(::System::Xml::Schema::XmlSchemaSet^  xs);
    };
    
    public : /// <summary>
///Represents strongly named DataRow class.
///</summary>
    ref class OrganicItemRow : public ::System::Data::DataRow {
        
        private: OrganicTbl::OrganicItemDataTable^  tableOrganicItem;
        
        internal: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        OrganicItemRow(::System::Data::DataRowBuilder^  rb);
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        property System::Int32 OrganicItemID {
            System::Int32 get();
            System::Void set(System::Int32 value);
        }
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        property System::String^  ItemInfo {
            System::String^  get();
            System::Void set(System::String^  value);
        }
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        property System::Int32 RequiredGem {
            System::Int32 get();
            System::Void set(System::Int32 value);
        }
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        property System::Int32 RequiredGameMoney {
            System::Int32 get();
            System::Void set(System::Int32 value);
        }
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        property System::String^  ItemEffect {
            System::String^  get();
            System::Void set(System::String^  value);
        }
    };
    
    public : /// <summary>
///Row event argument class
///</summary>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
    ref class OrganicItemRowChangeEvent : public ::System::EventArgs {
        
        private: OrganicTbl::OrganicItemRow^  eventRow;
        
        private: ::System::Data::DataRowAction eventAction;
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        OrganicItemRowChangeEvent(OrganicTbl::OrganicItemRow^  row, ::System::Data::DataRowAction action);
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        property OrganicTbl::OrganicItemRow^  Row {
            OrganicTbl::OrganicItemRow^  get();
        }
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        property ::System::Data::DataRowAction Action {
            ::System::Data::DataRowAction get();
        }
    };
};


inline OrganicTbl::OrganicTbl() {
    this->BeginInit();
    this->InitClass();
    ::System::ComponentModel::CollectionChangeEventHandler^  schemaChangedHandler = gcnew ::System::ComponentModel::CollectionChangeEventHandler(this, &OrganicTbl::SchemaChanged);
    __super::Tables->CollectionChanged += schemaChangedHandler;
    __super::Relations->CollectionChanged += schemaChangedHandler;
    this->EndInit();
}

inline OrganicTbl::OrganicTbl(::System::Runtime::Serialization::SerializationInfo^  info, ::System::Runtime::Serialization::StreamingContext context) : 
        ::System::Data::DataSet(info, context, false) {
    if (this->IsBinarySerialized(info, context) == true) {
        this->InitVars(false);
        ::System::ComponentModel::CollectionChangeEventHandler^  schemaChangedHandler1 = gcnew ::System::ComponentModel::CollectionChangeEventHandler(this, &OrganicTbl::SchemaChanged);
        this->Tables->CollectionChanged += schemaChangedHandler1;
        this->Relations->CollectionChanged += schemaChangedHandler1;
        return;
    }
    ::System::String^  strSchema = (cli::safe_cast<::System::String^  >(info->GetValue(L"XmlSchema", ::System::String::typeid)));
    if (this->DetermineSchemaSerializationMode(info, context) == ::System::Data::SchemaSerializationMode::IncludeSchema) {
        ::System::Data::DataSet^  ds = (gcnew ::System::Data::DataSet());
        ds->ReadXmlSchema((gcnew ::System::Xml::XmlTextReader((gcnew ::System::IO::StringReader(strSchema)))));
        if (ds->Tables[L"OrganicItem"] != nullptr) {
            __super::Tables->Add((gcnew OrganicTbl::OrganicItemDataTable(ds->Tables[L"OrganicItem"])));
        }
        this->DataSetName = ds->DataSetName;
        this->Prefix = ds->Prefix;
        this->Namespace = ds->Namespace;
        this->Locale = ds->Locale;
        this->CaseSensitive = ds->CaseSensitive;
        this->EnforceConstraints = ds->EnforceConstraints;
        this->Merge(ds, false, ::System::Data::MissingSchemaAction::Add);
        this->InitVars();
    }
    else {
        this->ReadXmlSchema((gcnew ::System::Xml::XmlTextReader((gcnew ::System::IO::StringReader(strSchema)))));
    }
    this->GetSerializationData(info, context);
    ::System::ComponentModel::CollectionChangeEventHandler^  schemaChangedHandler = gcnew ::System::ComponentModel::CollectionChangeEventHandler(this, &OrganicTbl::SchemaChanged);
    __super::Tables->CollectionChanged += schemaChangedHandler;
    this->Relations->CollectionChanged += schemaChangedHandler;
}

inline OrganicTbl::OrganicItemDataTable^  OrganicTbl::OrganicItem::get() {
    return this->tableOrganicItem;
}

inline ::System::Data::SchemaSerializationMode OrganicTbl::SchemaSerializationMode::get() {
    return this->_schemaSerializationMode;
}
inline System::Void OrganicTbl::SchemaSerializationMode::set(::System::Data::SchemaSerializationMode value) {
    this->_schemaSerializationMode = __identifier(value);
}

inline ::System::Data::DataTableCollection^  OrganicTbl::Tables::get() {
    return __super::Tables;
}

inline ::System::Data::DataRelationCollection^  OrganicTbl::Relations::get() {
    return __super::Relations;
}

inline ::System::Void OrganicTbl::InitializeDerivedDataSet() {
    this->BeginInit();
    this->InitClass();
    this->EndInit();
}

inline ::System::Data::DataSet^  OrganicTbl::Clone() {
    OrganicTbl^  cln = (cli::safe_cast<OrganicTbl^  >(__super::Clone()));
    cln->InitVars();
    cln->SchemaSerializationMode = this->SchemaSerializationMode;
    return cln;
}

inline ::System::Boolean OrganicTbl::ShouldSerializeTables() {
    return false;
}

inline ::System::Boolean OrganicTbl::ShouldSerializeRelations() {
    return false;
}

inline ::System::Void OrganicTbl::ReadXmlSerializable(::System::Xml::XmlReader^  reader) {
    if (this->DetermineSchemaSerializationMode(reader) == ::System::Data::SchemaSerializationMode::IncludeSchema) {
        this->Reset();
        ::System::Data::DataSet^  ds = (gcnew ::System::Data::DataSet());
        ds->ReadXml(reader);
        if (ds->Tables[L"OrganicItem"] != nullptr) {
            __super::Tables->Add((gcnew OrganicTbl::OrganicItemDataTable(ds->Tables[L"OrganicItem"])));
        }
        this->DataSetName = ds->DataSetName;
        this->Prefix = ds->Prefix;
        this->Namespace = ds->Namespace;
        this->Locale = ds->Locale;
        this->CaseSensitive = ds->CaseSensitive;
        this->EnforceConstraints = ds->EnforceConstraints;
        this->Merge(ds, false, ::System::Data::MissingSchemaAction::Add);
        this->InitVars();
    }
    else {
        this->ReadXml(reader);
        this->InitVars();
    }
}

inline ::System::Xml::Schema::XmlSchema^  OrganicTbl::GetSchemaSerializable() {
    ::System::IO::MemoryStream^  stream = (gcnew ::System::IO::MemoryStream());
    this->WriteXmlSchema((gcnew ::System::Xml::XmlTextWriter(stream, nullptr)));
    stream->Position = 0;
    return ::System::Xml::Schema::XmlSchema::Read((gcnew ::System::Xml::XmlTextReader(stream)), nullptr);
}

inline ::System::Void OrganicTbl::InitVars() {
    this->InitVars(true);
}

inline ::System::Void OrganicTbl::InitVars(::System::Boolean initTable) {
    this->tableOrganicItem = (cli::safe_cast<OrganicTbl::OrganicItemDataTable^  >(__super::Tables[L"OrganicItem"]));
    if (initTable == true) {
        if (this->tableOrganicItem != nullptr) {
            this->tableOrganicItem->InitVars();
        }
    }
}

inline ::System::Void OrganicTbl::InitClass() {
    this->DataSetName = L"OrganicTbl";
    this->Prefix = L"";
    this->EnforceConstraints = true;
    this->SchemaSerializationMode = ::System::Data::SchemaSerializationMode::IncludeSchema;
    this->tableOrganicItem = (gcnew OrganicTbl::OrganicItemDataTable());
    __super::Tables->Add(this->tableOrganicItem);
}

inline ::System::Boolean OrganicTbl::ShouldSerializeOrganicItem() {
    return false;
}

inline ::System::Void OrganicTbl::SchemaChanged(::System::Object^  sender, ::System::ComponentModel::CollectionChangeEventArgs^  e) {
    if (e->Action == ::System::ComponentModel::CollectionChangeAction::Remove) {
        this->InitVars();
    }
}

inline ::System::Xml::Schema::XmlSchemaComplexType^  OrganicTbl::GetTypedDataSetSchema(::System::Xml::Schema::XmlSchemaSet^  xs) {
    OrganicTbl^  ds = (gcnew OrganicTbl());
    ::System::Xml::Schema::XmlSchemaComplexType^  type = (gcnew ::System::Xml::Schema::XmlSchemaComplexType());
    ::System::Xml::Schema::XmlSchemaSequence^  sequence = (gcnew ::System::Xml::Schema::XmlSchemaSequence());
    ::System::Xml::Schema::XmlSchemaAny^  any = (gcnew ::System::Xml::Schema::XmlSchemaAny());
    any->Namespace = ds->Namespace;
    sequence->Items->Add(any);
    type->Particle = sequence;
    ::System::Xml::Schema::XmlSchema^  dsSchema = ds->GetSchemaSerializable();
    if (xs->Contains(dsSchema->TargetNamespace)) {
        ::System::IO::MemoryStream^  s1 = (gcnew ::System::IO::MemoryStream());
        ::System::IO::MemoryStream^  s2 = (gcnew ::System::IO::MemoryStream());
        try {
            ::System::Xml::Schema::XmlSchema^  schema = nullptr;
            dsSchema->Write(s1);
            for (            ::System::Collections::IEnumerator^  schemas = xs->Schemas(dsSchema->TargetNamespace)->GetEnumerator(); schemas->MoveNext();             ) {
                schema = (cli::safe_cast<::System::Xml::Schema::XmlSchema^  >(schemas->Current));
                s2->SetLength(0);
                schema->Write(s2);
                if (s1->Length == s2->Length) {
                    s1->Position = 0;
                    s2->Position = 0;
                    for (                    ; ((s1->Position != s1->Length) 
                                && (s1->ReadByte() == s2->ReadByte()));                     ) {
                        ;
                    }
                    if (s1->Position == s1->Length) {
                        return type;
                    }
                }
            }
        }
        finally {
            if (s1 != nullptr) {
                s1->Close();
            }
            if (s2 != nullptr) {
                s2->Close();
            }
        }
    }
    xs->Add(dsSchema);
    return type;
}


inline OrganicTbl::OrganicItemDataTable::OrganicItemDataTable() {
    this->TableName = L"OrganicItem";
    this->BeginInit();
    this->InitClass();
    this->EndInit();
}

inline OrganicTbl::OrganicItemDataTable::OrganicItemDataTable(::System::Data::DataTable^  table) {
    this->TableName = table->TableName;
    if (table->CaseSensitive != table->DataSet->CaseSensitive) {
        this->CaseSensitive = table->CaseSensitive;
    }
    if (table->Locale->ToString() != table->DataSet->Locale->ToString()) {
        this->Locale = table->Locale;
    }
    if (table->Namespace != table->DataSet->Namespace) {
        this->Namespace = table->Namespace;
    }
    this->Prefix = table->Prefix;
    this->MinimumCapacity = table->MinimumCapacity;
}

inline OrganicTbl::OrganicItemDataTable::OrganicItemDataTable(::System::Runtime::Serialization::SerializationInfo^  info, 
            ::System::Runtime::Serialization::StreamingContext context) : 
        ::System::Data::DataTable(info, context) {
    this->InitVars();
}

inline ::System::Data::DataColumn^  OrganicTbl::OrganicItemDataTable::OrganicItemIDColumn::get() {
    return this->columnOrganicItemID;
}

inline ::System::Data::DataColumn^  OrganicTbl::OrganicItemDataTable::ItemInfoColumn::get() {
    return this->columnItemInfo;
}

inline ::System::Data::DataColumn^  OrganicTbl::OrganicItemDataTable::RequiredGemColumn::get() {
    return this->columnRequiredGem;
}

inline ::System::Data::DataColumn^  OrganicTbl::OrganicItemDataTable::RequiredGameMoneyColumn::get() {
    return this->columnRequiredGameMoney;
}

inline ::System::Data::DataColumn^  OrganicTbl::OrganicItemDataTable::ItemEffectColumn::get() {
    return this->columnItemEffect;
}

inline ::System::Int32 OrganicTbl::OrganicItemDataTable::Count::get() {
    return this->Rows->Count;
}

inline OrganicTbl::OrganicItemRow^  OrganicTbl::OrganicItemDataTable::default::get(::System::Int32 index) {
    return (cli::safe_cast<OrganicTbl::OrganicItemRow^  >(this->Rows[index]));
}

inline ::System::Void OrganicTbl::OrganicItemDataTable::AddOrganicItemRow(OrganicTbl::OrganicItemRow^  row) {
    this->Rows->Add(row);
}

inline OrganicTbl::OrganicItemRow^  OrganicTbl::OrganicItemDataTable::AddOrganicItemRow(System::Int32 OrganicItemID, System::String^  ItemInfo, 
            System::Int32 RequiredGem, System::Int32 RequiredGameMoney, System::String^  ItemEffect) {
    OrganicTbl::OrganicItemRow^  rowOrganicItemRow = (cli::safe_cast<OrganicTbl::OrganicItemRow^  >(this->NewRow()));
    cli::array< ::System::Object^  >^  columnValuesArray = gcnew cli::array< ::System::Object^  >(5) {OrganicItemID, ItemInfo, 
        RequiredGem, RequiredGameMoney, ItemEffect};
    rowOrganicItemRow->ItemArray = columnValuesArray;
    this->Rows->Add(rowOrganicItemRow);
    return rowOrganicItemRow;
}

inline ::System::Collections::IEnumerator^  OrganicTbl::OrganicItemDataTable::GetEnumerator() {
    return this->Rows->GetEnumerator();
}

inline ::System::Data::DataTable^  OrganicTbl::OrganicItemDataTable::Clone() {
    OrganicTbl::OrganicItemDataTable^  cln = (cli::safe_cast<OrganicTbl::OrganicItemDataTable^  >(__super::Clone()));
    cln->InitVars();
    return cln;
}

inline ::System::Data::DataTable^  OrganicTbl::OrganicItemDataTable::CreateInstance() {
    return (gcnew OrganicTbl::OrganicItemDataTable());
}

inline ::System::Void OrganicTbl::OrganicItemDataTable::InitVars() {
    this->columnOrganicItemID = __super::Columns[L"OrganicItemID"];
    this->columnItemInfo = __super::Columns[L"ItemInfo"];
    this->columnRequiredGem = __super::Columns[L"RequiredGem"];
    this->columnRequiredGameMoney = __super::Columns[L"RequiredGameMoney"];
    this->columnItemEffect = __super::Columns[L"ItemEffect"];
}

inline ::System::Void OrganicTbl::OrganicItemDataTable::InitClass() {
    this->columnOrganicItemID = (gcnew ::System::Data::DataColumn(L"OrganicItemID", ::System::Int32::typeid, nullptr, ::System::Data::MappingType::Attribute));
    __super::Columns->Add(this->columnOrganicItemID);
    this->columnItemInfo = (gcnew ::System::Data::DataColumn(L"ItemInfo", ::System::String::typeid, nullptr, ::System::Data::MappingType::Attribute));
    __super::Columns->Add(this->columnItemInfo);
    this->columnRequiredGem = (gcnew ::System::Data::DataColumn(L"RequiredGem", ::System::Int32::typeid, nullptr, ::System::Data::MappingType::Attribute));
    __super::Columns->Add(this->columnRequiredGem);
    this->columnRequiredGameMoney = (gcnew ::System::Data::DataColumn(L"RequiredGameMoney", ::System::Int32::typeid, nullptr, ::System::Data::MappingType::Attribute));
    __super::Columns->Add(this->columnRequiredGameMoney);
    this->columnItemEffect = (gcnew ::System::Data::DataColumn(L"ItemEffect", ::System::String::typeid, nullptr, ::System::Data::MappingType::Attribute));
    __super::Columns->Add(this->columnItemEffect);
    this->columnOrganicItemID->AllowDBNull = false;
    this->columnOrganicItemID->Namespace = L"";
    this->columnItemInfo->AllowDBNull = false;
    this->columnItemInfo->Namespace = L"";
    this->columnRequiredGem->AllowDBNull = false;
    this->columnRequiredGem->Namespace = L"";
    this->columnRequiredGameMoney->AllowDBNull = false;
    this->columnRequiredGameMoney->Namespace = L"";
    this->columnItemEffect->AllowDBNull = false;
    this->columnItemEffect->Namespace = L"";
}

inline OrganicTbl::OrganicItemRow^  OrganicTbl::OrganicItemDataTable::NewOrganicItemRow() {
    return (cli::safe_cast<OrganicTbl::OrganicItemRow^  >(this->NewRow()));
}

inline ::System::Data::DataRow^  OrganicTbl::OrganicItemDataTable::NewRowFromBuilder(::System::Data::DataRowBuilder^  builder) {
    return (gcnew OrganicTbl::OrganicItemRow(builder));
}

inline ::System::Type^  OrganicTbl::OrganicItemDataTable::GetRowType() {
    return OrganicTbl::OrganicItemRow::typeid;
}

inline ::System::Void OrganicTbl::OrganicItemDataTable::OnRowChanged(::System::Data::DataRowChangeEventArgs^  e) {
    __super::OnRowChanged(e);
    {
        this->OrganicItemRowChanged(this, (gcnew OrganicTbl::OrganicItemRowChangeEvent((cli::safe_cast<OrganicTbl::OrganicItemRow^  >(e->Row)), 
                e->Action)));
    }
}

inline ::System::Void OrganicTbl::OrganicItemDataTable::OnRowChanging(::System::Data::DataRowChangeEventArgs^  e) {
    __super::OnRowChanging(e);
    {
        this->OrganicItemRowChanging(this, (gcnew OrganicTbl::OrganicItemRowChangeEvent((cli::safe_cast<OrganicTbl::OrganicItemRow^  >(e->Row)), 
                e->Action)));
    }
}

inline ::System::Void OrganicTbl::OrganicItemDataTable::OnRowDeleted(::System::Data::DataRowChangeEventArgs^  e) {
    __super::OnRowDeleted(e);
    {
        this->OrganicItemRowDeleted(this, (gcnew OrganicTbl::OrganicItemRowChangeEvent((cli::safe_cast<OrganicTbl::OrganicItemRow^  >(e->Row)), 
                e->Action)));
    }
}

inline ::System::Void OrganicTbl::OrganicItemDataTable::OnRowDeleting(::System::Data::DataRowChangeEventArgs^  e) {
    __super::OnRowDeleting(e);
    {
        this->OrganicItemRowDeleting(this, (gcnew OrganicTbl::OrganicItemRowChangeEvent((cli::safe_cast<OrganicTbl::OrganicItemRow^  >(e->Row)), 
                e->Action)));
    }
}

inline ::System::Void OrganicTbl::OrganicItemDataTable::RemoveOrganicItemRow(OrganicTbl::OrganicItemRow^  row) {
    this->Rows->Remove(row);
}

inline ::System::Xml::Schema::XmlSchemaComplexType^  OrganicTbl::OrganicItemDataTable::GetTypedTableSchema(::System::Xml::Schema::XmlSchemaSet^  xs) {
    ::System::Xml::Schema::XmlSchemaComplexType^  type = (gcnew ::System::Xml::Schema::XmlSchemaComplexType());
    ::System::Xml::Schema::XmlSchemaSequence^  sequence = (gcnew ::System::Xml::Schema::XmlSchemaSequence());
    OrganicTbl^  ds = (gcnew OrganicTbl());
    ::System::Xml::Schema::XmlSchemaAny^  any1 = (gcnew ::System::Xml::Schema::XmlSchemaAny());
    any1->Namespace = L"http://www.w3.org/2001/XMLSchema";
    any1->MinOccurs = ::System::Decimal(0);
    any1->MaxOccurs = ::System::Decimal::MaxValue;
    any1->ProcessContents = ::System::Xml::Schema::XmlSchemaContentProcessing::Lax;
    sequence->Items->Add(any1);
    ::System::Xml::Schema::XmlSchemaAny^  any2 = (gcnew ::System::Xml::Schema::XmlSchemaAny());
    any2->Namespace = L"urn:schemas-microsoft-com:xml-diffgram-v1";
    any2->MinOccurs = ::System::Decimal(1);
    any2->ProcessContents = ::System::Xml::Schema::XmlSchemaContentProcessing::Lax;
    sequence->Items->Add(any2);
    ::System::Xml::Schema::XmlSchemaAttribute^  attribute1 = (gcnew ::System::Xml::Schema::XmlSchemaAttribute());
    attribute1->Name = L"namespace";
    attribute1->FixedValue = ds->Namespace;
    type->Attributes->Add(attribute1);
    ::System::Xml::Schema::XmlSchemaAttribute^  attribute2 = (gcnew ::System::Xml::Schema::XmlSchemaAttribute());
    attribute2->Name = L"tableTypeName";
    attribute2->FixedValue = L"OrganicItemDataTable";
    type->Attributes->Add(attribute2);
    type->Particle = sequence;
    ::System::Xml::Schema::XmlSchema^  dsSchema = ds->GetSchemaSerializable();
    if (xs->Contains(dsSchema->TargetNamespace)) {
        ::System::IO::MemoryStream^  s1 = (gcnew ::System::IO::MemoryStream());
        ::System::IO::MemoryStream^  s2 = (gcnew ::System::IO::MemoryStream());
        try {
            ::System::Xml::Schema::XmlSchema^  schema = nullptr;
            dsSchema->Write(s1);
            for (            ::System::Collections::IEnumerator^  schemas = xs->Schemas(dsSchema->TargetNamespace)->GetEnumerator(); schemas->MoveNext();             ) {
                schema = (cli::safe_cast<::System::Xml::Schema::XmlSchema^  >(schemas->Current));
                s2->SetLength(0);
                schema->Write(s2);
                if (s1->Length == s2->Length) {
                    s1->Position = 0;
                    s2->Position = 0;
                    for (                    ; ((s1->Position != s1->Length) 
                                && (s1->ReadByte() == s2->ReadByte()));                     ) {
                        ;
                    }
                    if (s1->Position == s1->Length) {
                        return type;
                    }
                }
            }
        }
        finally {
            if (s1 != nullptr) {
                s1->Close();
            }
            if (s2 != nullptr) {
                s2->Close();
            }
        }
    }
    xs->Add(dsSchema);
    return type;
}


inline OrganicTbl::OrganicItemRow::OrganicItemRow(::System::Data::DataRowBuilder^  rb) : 
        ::System::Data::DataRow(rb) {
    this->tableOrganicItem = (cli::safe_cast<OrganicTbl::OrganicItemDataTable^  >(this->Table));
}

inline System::Int32 OrganicTbl::OrganicItemRow::OrganicItemID::get() {
    return (cli::safe_cast<::System::Int32 >(this[this->tableOrganicItem->OrganicItemIDColumn]));
}
inline System::Void OrganicTbl::OrganicItemRow::OrganicItemID::set(System::Int32 value) {
    this[this->tableOrganicItem->OrganicItemIDColumn] = value;
}

inline System::String^  OrganicTbl::OrganicItemRow::ItemInfo::get() {
    return (cli::safe_cast<::System::String^  >(this[this->tableOrganicItem->ItemInfoColumn]));
}
inline System::Void OrganicTbl::OrganicItemRow::ItemInfo::set(System::String^  value) {
    this[this->tableOrganicItem->ItemInfoColumn] = value;
}

inline System::Int32 OrganicTbl::OrganicItemRow::RequiredGem::get() {
    return (cli::safe_cast<::System::Int32 >(this[this->tableOrganicItem->RequiredGemColumn]));
}
inline System::Void OrganicTbl::OrganicItemRow::RequiredGem::set(System::Int32 value) {
    this[this->tableOrganicItem->RequiredGemColumn] = value;
}

inline System::Int32 OrganicTbl::OrganicItemRow::RequiredGameMoney::get() {
    return (cli::safe_cast<::System::Int32 >(this[this->tableOrganicItem->RequiredGameMoneyColumn]));
}
inline System::Void OrganicTbl::OrganicItemRow::RequiredGameMoney::set(System::Int32 value) {
    this[this->tableOrganicItem->RequiredGameMoneyColumn] = value;
}

inline System::String^  OrganicTbl::OrganicItemRow::ItemEffect::get() {
    return (cli::safe_cast<::System::String^  >(this[this->tableOrganicItem->ItemEffectColumn]));
}
inline System::Void OrganicTbl::OrganicItemRow::ItemEffect::set(System::String^  value) {
    this[this->tableOrganicItem->ItemEffectColumn] = value;
}


inline OrganicTbl::OrganicItemRowChangeEvent::OrganicItemRowChangeEvent(OrganicTbl::OrganicItemRow^  row, ::System::Data::DataRowAction action) {
    this->eventRow = row;
    this->eventAction = action;
}

inline OrganicTbl::OrganicItemRow^  OrganicTbl::OrganicItemRowChangeEvent::Row::get() {
    return this->eventRow;
}

inline ::System::Data::DataRowAction OrganicTbl::OrganicItemRowChangeEvent::Action::get() {
    return this->eventAction;
}
