////////////////////////////////////////////////////////////////////////////////
// 
// CopyRight (c) 2016 Blue3k
// 
// Author : KyungKun Ko
//
// Description : Autogenerated file, System
//
////////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Serialization;


namespace BR {
	public partial struct ResultCode {

		// Success 
		const uint S_SYSTEM_FALSE =                                         unchecked(0x20000000); 

		// Invalid pointer 
		const uint E_SYSTEM_POINTER =                                       unchecked(0xE0000001); 

		// Fail 
		const uint E_SYSTEM_FAIL =                                          unchecked(0xE0000002); 

		// Not implemented 
		const uint E_SYSTEM_NOTIMPL =                                       unchecked(0xE0000003); 

		// Out of memory 
		const uint E_SYSTEM_OUTOFMEMORY =                                   unchecked(0xE0000004); 

		// Unexpected 
		const uint E_SYSTEM_UNEXPECTED =                                    unchecked(0xE0000005); 

		// Invalid argument 
		const uint E_SYSTEM_INVALIDARG =                                    unchecked(0xE0000006); 

	}
}

