//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace GameTbl {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class clientSettingTable {
        
        private clientSettingTableClientSettingItem[] clientSettingItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("clientSettingItem")]
        public clientSettingTableClientSettingItem[] clientSettingItem {
            get {
                return this.clientSettingItemField;
            }
            set {
                this.clientSettingItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class clientSettingTableClientSettingItem {
        
        private float showVoteTimeField;
        
        private float hideVoteTimeField;
        
        private float killAnimationTimeField;
        
        private float freeDebateShowRoleField;
        
        private float freeDebatePhaseField;
        
        private float freeDebateDescription1Field;
        
        private float freeDebateDescription2Field;
        
        private float nightVotePhaseField;
        
        private float nightVoteDescriptionField;
        
        private float voteForSuspectsPhaseField;
        
        private float voteForSuspectsDescriptionField;
        
        private float voteForSuspectsResultField;
        
        private float voteForHangingPhase1Field;
        
        private float voteForHangingDescription1Field;
        
        private float voteForHangingPhase2Field;
        
        private float voteForHangingDescription2Field;
        
        private float voteForHangingDescription3Field;
        
        private float defenceOfSuspectsPhaseField;
        
        private float defenceOfSuspectsDescriptionField;
        
        private float endPhaseField;
        
        private float endDescription1Field;
        
        private float endDescription2Field;
        
        private float endDescription3Field;
        
        private float resultTurnField;
        
        private float endResult1Field;
        
        private float endResult2Field;
        
        private float endResult3Field;
        
        private float standByRoom_MessagePopupTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float ShowVoteTime {
            get {
                return this.showVoteTimeField;
            }
            set {
                this.showVoteTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float HideVoteTime {
            get {
                return this.hideVoteTimeField;
            }
            set {
                this.hideVoteTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float KillAnimationTime {
            get {
                return this.killAnimationTimeField;
            }
            set {
                this.killAnimationTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float FreeDebateShowRole {
            get {
                return this.freeDebateShowRoleField;
            }
            set {
                this.freeDebateShowRoleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float FreeDebatePhase {
            get {
                return this.freeDebatePhaseField;
            }
            set {
                this.freeDebatePhaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float FreeDebateDescription1 {
            get {
                return this.freeDebateDescription1Field;
            }
            set {
                this.freeDebateDescription1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float FreeDebateDescription2 {
            get {
                return this.freeDebateDescription2Field;
            }
            set {
                this.freeDebateDescription2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float NightVotePhase {
            get {
                return this.nightVotePhaseField;
            }
            set {
                this.nightVotePhaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float NightVoteDescription {
            get {
                return this.nightVoteDescriptionField;
            }
            set {
                this.nightVoteDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float VoteForSuspectsPhase {
            get {
                return this.voteForSuspectsPhaseField;
            }
            set {
                this.voteForSuspectsPhaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float VoteForSuspectsDescription {
            get {
                return this.voteForSuspectsDescriptionField;
            }
            set {
                this.voteForSuspectsDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float VoteForSuspectsResult {
            get {
                return this.voteForSuspectsResultField;
            }
            set {
                this.voteForSuspectsResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float VoteForHangingPhase1 {
            get {
                return this.voteForHangingPhase1Field;
            }
            set {
                this.voteForHangingPhase1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float VoteForHangingDescription1 {
            get {
                return this.voteForHangingDescription1Field;
            }
            set {
                this.voteForHangingDescription1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float VoteForHangingPhase2 {
            get {
                return this.voteForHangingPhase2Field;
            }
            set {
                this.voteForHangingPhase2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float VoteForHangingDescription2 {
            get {
                return this.voteForHangingDescription2Field;
            }
            set {
                this.voteForHangingDescription2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float VoteForHangingDescription3 {
            get {
                return this.voteForHangingDescription3Field;
            }
            set {
                this.voteForHangingDescription3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float DefenceOfSuspectsPhase {
            get {
                return this.defenceOfSuspectsPhaseField;
            }
            set {
                this.defenceOfSuspectsPhaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float DefenceOfSuspectsDescription {
            get {
                return this.defenceOfSuspectsDescriptionField;
            }
            set {
                this.defenceOfSuspectsDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float EndPhase {
            get {
                return this.endPhaseField;
            }
            set {
                this.endPhaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float EndDescription1 {
            get {
                return this.endDescription1Field;
            }
            set {
                this.endDescription1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float EndDescription2 {
            get {
                return this.endDescription2Field;
            }
            set {
                this.endDescription2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float EndDescription3 {
            get {
                return this.endDescription3Field;
            }
            set {
                this.endDescription3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float ResultTurn {
            get {
                return this.resultTurnField;
            }
            set {
                this.resultTurnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float EndResult1 {
            get {
                return this.endResult1Field;
            }
            set {
                this.endResult1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float EndResult2 {
            get {
                return this.endResult2Field;
            }
            set {
                this.endResult2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float EndResult3 {
            get {
                return this.endResult3Field;
            }
            set {
                this.endResult3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float StandByRoom_MessagePopupTime {
            get {
                return this.standByRoom_MessagePopupTimeField;
            }
            set {
                this.standByRoom_MessagePopupTimeField = value;
            }
        }
    }
}
