//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace GameTbl {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class GameConfigTbl {
        
        private GameConfigTblGameConfigItem[] gameConfigItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GameConfigItem")]
        public GameConfigTblGameConfigItem[] GameConfigItem {
            get {
                return this.gameConfigItemField;
            }
            set {
                this.gameConfigItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GameConfigTblGameConfigItem {
        
        private int presetIDField;
        
        private int defaultMailField;
        
        private int defaultGemField;
        
        private int maxGemField;
        
        private int defaultMoneyField;
        
        private int maxMoneyField;
        
        private int defaultFriendField;
        
        private int maxFriendField;
        
        private int defaultStaminaField;
        
        private int maxStaminaField;
        
        private int maxAutoRefilStaminaField;
        
        private int staminaRecoveryTimeField;
        
        private int staminaForGameField;
        
        private int freeDiscussionField;
        
        private int rolePlayTimeField;
        
        private int rolePlayAndKillingTimeField;
        
        private int firstVoteField;
        
        private int defenceTimeField;
        
        private int secondVoteField;
        
        private int morningDiscussionField;
        
        private int resultNoticeTimeField;
        
        private int playerDisplayOfflineField;
        
        private int maxCharacterSetField;
        
        private int forceProgressCountField;
        
        private int playerAutoLogoutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int PresetID {
            get {
                return this.presetIDField;
            }
            set {
                this.presetIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int DefaultMail {
            get {
                return this.defaultMailField;
            }
            set {
                this.defaultMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int DefaultGem {
            get {
                return this.defaultGemField;
            }
            set {
                this.defaultGemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int MaxGem {
            get {
                return this.maxGemField;
            }
            set {
                this.maxGemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int DefaultMoney {
            get {
                return this.defaultMoneyField;
            }
            set {
                this.defaultMoneyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int MaxMoney {
            get {
                return this.maxMoneyField;
            }
            set {
                this.maxMoneyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int DefaultFriend {
            get {
                return this.defaultFriendField;
            }
            set {
                this.defaultFriendField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int MaxFriend {
            get {
                return this.maxFriendField;
            }
            set {
                this.maxFriendField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int DefaultStamina {
            get {
                return this.defaultStaminaField;
            }
            set {
                this.defaultStaminaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int MaxStamina {
            get {
                return this.maxStaminaField;
            }
            set {
                this.maxStaminaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int MaxAutoRefilStamina {
            get {
                return this.maxAutoRefilStaminaField;
            }
            set {
                this.maxAutoRefilStaminaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int StaminaRecoveryTime {
            get {
                return this.staminaRecoveryTimeField;
            }
            set {
                this.staminaRecoveryTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int StaminaForGame {
            get {
                return this.staminaForGameField;
            }
            set {
                this.staminaForGameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int FreeDiscussion {
            get {
                return this.freeDiscussionField;
            }
            set {
                this.freeDiscussionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int RolePlayTime {
            get {
                return this.rolePlayTimeField;
            }
            set {
                this.rolePlayTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int RolePlayAndKillingTime {
            get {
                return this.rolePlayAndKillingTimeField;
            }
            set {
                this.rolePlayAndKillingTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int FirstVote {
            get {
                return this.firstVoteField;
            }
            set {
                this.firstVoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int DefenceTime {
            get {
                return this.defenceTimeField;
            }
            set {
                this.defenceTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int SecondVote {
            get {
                return this.secondVoteField;
            }
            set {
                this.secondVoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int MorningDiscussion {
            get {
                return this.morningDiscussionField;
            }
            set {
                this.morningDiscussionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ResultNoticeTime {
            get {
                return this.resultNoticeTimeField;
            }
            set {
                this.resultNoticeTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int PlayerDisplayOffline {
            get {
                return this.playerDisplayOfflineField;
            }
            set {
                this.playerDisplayOfflineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int MaxCharacterSet {
            get {
                return this.maxCharacterSetField;
            }
            set {
                this.maxCharacterSetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ForceProgressCount {
            get {
                return this.forceProgressCountField;
            }
            set {
                this.forceProgressCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int PlayerAutoLogout {
            get {
                return this.playerAutoLogoutField;
            }
            set {
                this.playerAutoLogoutField = value;
            }
        }
    }
}
