//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 
namespace conspiracy {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ShopTbl {
        
        private ShopTblShopItem[] shopItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShopItem")]
        public ShopTblShopItem[] ShopItem {
            get {
                return this.shopItemField;
            }
            set {
                this.shopItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ShopTblShopItem {
        
        private int shopItemIDField;
        
        private string itemInfoField;
        
        private string requiredCashField;
        
        private int requiredGemField;
        
        private int requiredGameMoneyField;
        
        private ShopTblShopItemItemEffect itemEffectField;
        
        private int quantityField;
        
        private string androidItemIDField;
        
        private string iOSItemIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ShopItemID {
            get {
                return this.shopItemIDField;
            }
            set {
                this.shopItemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemInfo {
            get {
                return this.itemInfoField;
            }
            set {
                this.itemInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RequiredCash {
            get {
                return this.requiredCashField;
            }
            set {
                this.requiredCashField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int RequiredGem {
            get {
                return this.requiredGemField;
            }
            set {
                this.requiredGemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int RequiredGameMoney {
            get {
                return this.requiredGameMoneyField;
            }
            set {
                this.requiredGameMoneyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ShopTblShopItemItemEffect ItemEffect {
            get {
                return this.itemEffectField;
            }
            set {
                this.itemEffectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AndroidItemID {
            get {
                return this.androidItemIDField;
            }
            set {
                this.androidItemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string iOSItemID {
            get {
                return this.iOSItemIDField;
            }
            set {
                this.iOSItemIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ShopTblShopItemItemEffect {
        
        /// <remarks/>
        Gem,
        
        /// <remarks/>
        Stamina,
        
        /// <remarks/>
        FriendSlot,
    }
}
