//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace conspiracy {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class RewardTbl {
        
        private RewardTblRewardItem[] rewardItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RewardItem")]
        public RewardTblRewardItem[] RewardItem {
            get {
                return this.rewardItemField;
            }
            set {
                this.rewardItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RewardTblRewardItem {
        
        private RewardTblRewardItemRole roleField;
        
        private int winExpField;
        
        private int loseExpField;
        
        private int winMoneyField;
        
        private int loseMoneyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RewardTblRewardItemRole Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int WinExp {
            get {
                return this.winExpField;
            }
            set {
                this.winExpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int LoseExp {
            get {
                return this.loseExpField;
            }
            set {
                this.loseExpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int WinMoney {
            get {
                return this.winMoneyField;
            }
            set {
                this.winMoneyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int LoseMoney {
            get {
                return this.loseMoneyField;
            }
            set {
                this.loseMoneyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum RewardTblRewardItemRole {
        
        /// <remarks/>
        Villager,
        
        /// <remarks/>
        Monster,
        
        /// <remarks/>
        Seer,
    }
}
